// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_mocguestagent_certificate.proto

package security

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CertificateRequest struct {
	Certificates         []*Certificate `protobuf:"bytes,1,rep,name=Certificates,proto3" json:"Certificates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CertificateRequest) Reset()         { *m = CertificateRequest{} }
func (m *CertificateRequest) String() string { return proto.CompactTextString(m) }
func (*CertificateRequest) ProtoMessage()    {}
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3663d8a2d284fe24, []int{0}
}

func (m *CertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateRequest.Unmarshal(m, b)
}
func (m *CertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateRequest.Marshal(b, m, deterministic)
}
func (m *CertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateRequest.Merge(m, src)
}
func (m *CertificateRequest) XXX_Size() int {
	return xxx_messageInfo_CertificateRequest.Size(m)
}
func (m *CertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateRequest proto.InternalMessageInfo

func (m *CertificateRequest) GetCertificates() []*Certificate {
	if m != nil {
		return m.Certificates
	}
	return nil
}

type CertificateResponse struct {
	Certificates         []*Certificate      `protobuf:"bytes,1,rep,name=Certificates,proto3" json:"Certificates,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CertificateResponse) Reset()         { *m = CertificateResponse{} }
func (m *CertificateResponse) String() string { return proto.CompactTextString(m) }
func (*CertificateResponse) ProtoMessage()    {}
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3663d8a2d284fe24, []int{1}
}

func (m *CertificateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateResponse.Unmarshal(m, b)
}
func (m *CertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateResponse.Marshal(b, m, deterministic)
}
func (m *CertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateResponse.Merge(m, src)
}
func (m *CertificateResponse) XXX_Size() int {
	return xxx_messageInfo_CertificateResponse.Size(m)
}
func (m *CertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateResponse proto.InternalMessageInfo

func (m *CertificateResponse) GetCertificates() []*Certificate {
	if m != nil {
		return m.Certificates
	}
	return nil
}

func (m *CertificateResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CertificateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Certificate struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	NotBefore            int64          `protobuf:"varint,3,opt,name=notBefore,proto3" json:"notBefore,omitempty"`
	NotAfter             int64          `protobuf:"varint,4,opt,name=notAfter,proto3" json:"notAfter,omitempty"`
	Certificate          string         `protobuf:"bytes,5,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Status               *common.Status `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	GroupName            string         `protobuf:"bytes,7,opt,name=groupName,proto3" json:"groupName,omitempty"`
	VaultName            string         `protobuf:"bytes,8,opt,name=vaultName,proto3" json:"vaultName,omitempty"`
	LocationName         string         `protobuf:"bytes,9,opt,name=locationName,proto3" json:"locationName,omitempty"`
	Tags                 *common.Tags   `protobuf:"bytes,10,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3663d8a2d284fe24, []int{2}
}

func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (m *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(m, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Certificate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Certificate) GetNotBefore() int64 {
	if m != nil {
		return m.NotBefore
	}
	return 0
}

func (m *Certificate) GetNotAfter() int64 {
	if m != nil {
		return m.NotAfter
	}
	return 0
}

func (m *Certificate) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *Certificate) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Certificate) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Certificate) GetVaultName() string {
	if m != nil {
		return m.VaultName
	}
	return ""
}

func (m *Certificate) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

func (m *Certificate) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CSRRequest struct {
	CSRs                 []*CertificateSigningRequest `protobuf:"bytes,1,rep,name=CSRs,proto3" json:"CSRs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CSRRequest) Reset()         { *m = CSRRequest{} }
func (m *CSRRequest) String() string { return proto.CompactTextString(m) }
func (*CSRRequest) ProtoMessage()    {}
func (*CSRRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3663d8a2d284fe24, []int{3}
}

func (m *CSRRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSRRequest.Unmarshal(m, b)
}
func (m *CSRRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSRRequest.Marshal(b, m, deterministic)
}
func (m *CSRRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSRRequest.Merge(m, src)
}
func (m *CSRRequest) XXX_Size() int {
	return xxx_messageInfo_CSRRequest.Size(m)
}
func (m *CSRRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CSRRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CSRRequest proto.InternalMessageInfo

func (m *CSRRequest) GetCSRs() []*CertificateSigningRequest {
	if m != nil {
		return m.CSRs
	}
	return nil
}

type CertificateSigningRequest struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Csr                  string         `protobuf:"bytes,2,opt,name=csr,proto3" json:"csr,omitempty"`
	OldCertificate       string         `protobuf:"bytes,3,opt,name=oldCertificate,proto3" json:"oldCertificate,omitempty"`
	Status               *common.Status `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CaName               string         `protobuf:"bytes,5,opt,name=caName,proto3" json:"caName,omitempty"`
	GroupName            string         `protobuf:"bytes,6,opt,name=groupName,proto3" json:"groupName,omitempty"`
	VaultName            string         `protobuf:"bytes,7,opt,name=vaultName,proto3" json:"vaultName,omitempty"`
	LocationName         string         `protobuf:"bytes,8,opt,name=locationName,proto3" json:"locationName,omitempty"`
	Validity             int64          `protobuf:"varint,9,opt,name=validity,proto3" json:"validity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CertificateSigningRequest) Reset()         { *m = CertificateSigningRequest{} }
func (m *CertificateSigningRequest) String() string { return proto.CompactTextString(m) }
func (*CertificateSigningRequest) ProtoMessage()    {}
func (*CertificateSigningRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3663d8a2d284fe24, []int{4}
}

func (m *CertificateSigningRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateSigningRequest.Unmarshal(m, b)
}
func (m *CertificateSigningRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateSigningRequest.Marshal(b, m, deterministic)
}
func (m *CertificateSigningRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateSigningRequest.Merge(m, src)
}
func (m *CertificateSigningRequest) XXX_Size() int {
	return xxx_messageInfo_CertificateSigningRequest.Size(m)
}
func (m *CertificateSigningRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateSigningRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateSigningRequest proto.InternalMessageInfo

func (m *CertificateSigningRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CertificateSigningRequest) GetCsr() string {
	if m != nil {
		return m.Csr
	}
	return ""
}

func (m *CertificateSigningRequest) GetOldCertificate() string {
	if m != nil {
		return m.OldCertificate
	}
	return ""
}

func (m *CertificateSigningRequest) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CertificateSigningRequest) GetCaName() string {
	if m != nil {
		return m.CaName
	}
	return ""
}

func (m *CertificateSigningRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *CertificateSigningRequest) GetVaultName() string {
	if m != nil {
		return m.VaultName
	}
	return ""
}

func (m *CertificateSigningRequest) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

func (m *CertificateSigningRequest) GetValidity() int64 {
	if m != nil {
		return m.Validity
	}
	return 0
}

type RenewCSRResponse struct {
	Csr                  *CertificateSigningRequest `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	Result               *wrappers.BoolValue        `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string                     `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RenewCSRResponse) Reset()         { *m = RenewCSRResponse{} }
func (m *RenewCSRResponse) String() string { return proto.CompactTextString(m) }
func (*RenewCSRResponse) ProtoMessage()    {}
func (*RenewCSRResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3663d8a2d284fe24, []int{5}
}

func (m *RenewCSRResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewCSRResponse.Unmarshal(m, b)
}
func (m *RenewCSRResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewCSRResponse.Marshal(b, m, deterministic)
}
func (m *RenewCSRResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewCSRResponse.Merge(m, src)
}
func (m *RenewCSRResponse) XXX_Size() int {
	return xxx_messageInfo_RenewCSRResponse.Size(m)
}
func (m *RenewCSRResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewCSRResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenewCSRResponse proto.InternalMessageInfo

func (m *RenewCSRResponse) GetCsr() *CertificateSigningRequest {
	if m != nil {
		return m.Csr
	}
	return nil
}

func (m *RenewCSRResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RenewCSRResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CertificateRequest)(nil), "moc.mocguestagent.security.CertificateRequest")
	proto.RegisterType((*CertificateResponse)(nil), "moc.mocguestagent.security.CertificateResponse")
	proto.RegisterType((*Certificate)(nil), "moc.mocguestagent.security.Certificate")
	proto.RegisterType((*CSRRequest)(nil), "moc.mocguestagent.security.CSRRequest")
	proto.RegisterType((*CertificateSigningRequest)(nil), "moc.mocguestagent.security.CertificateSigningRequest")
	proto.RegisterType((*RenewCSRResponse)(nil), "moc.mocguestagent.security.RenewCSRResponse")
}

func init() {
	proto.RegisterFile("moc_mocguestagent_certificate.proto", fileDescriptor_3663d8a2d284fe24)
}

var fileDescriptor_3663d8a2d284fe24 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0xfd, 0x9c, 0x84, 0x90, 0x4c, 0x10, 0xe2, 0xdb, 0x56, 0xd4, 0x75, 0x7f, 0x84, 0x8c, 0xd4,
	0x72, 0x81, 0x6c, 0x29, 0x88, 0x07, 0x20, 0x08, 0xa1, 0xaa, 0x52, 0x2f, 0x36, 0xfd, 0x91, 0x7a,
	0x83, 0x96, 0xcd, 0xc6, 0xb5, 0x64, 0x7b, 0xdc, 0xdd, 0x35, 0x88, 0x37, 0xe8, 0x8b, 0xf4, 0xae,
	0xea, 0x5d, 0xd5, 0xe7, 0xe9, 0x9b, 0x54, 0x1e, 0x3b, 0x60, 0x53, 0xa0, 0x51, 0xc5, 0x55, 0xb2,
	0x73, 0xc6, 0x67, 0xce, 0x9c, 0x63, 0x2f, 0x6c, 0xa7, 0x28, 0x4f, 0x52, 0x94, 0x51, 0xa1, 0x8c,
	0x15, 0x91, 0xca, 0xec, 0x89, 0x54, 0xda, 0xc6, 0xf3, 0x58, 0x0a, 0xab, 0x82, 0x5c, 0xa3, 0x45,
	0xe6, 0xa5, 0x28, 0x83, 0x56, 0x53, 0x60, 0x94, 0x2c, 0x74, 0x6c, 0x2f, 0xbc, 0xe7, 0x11, 0x62,
	0x94, 0xa8, 0x90, 0x3a, 0x4f, 0x8b, 0x79, 0x78, 0xae, 0x45, 0x9e, 0x2b, 0x6d, 0xaa, 0x67, 0xbd,
	0x27, 0xd7, 0x71, 0x95, 0xe6, 0xf6, 0xa2, 0x06, 0x1f, 0x95, 0xd3, 0x25, 0xa6, 0x29, 0x66, 0xf5,
	0x4f, 0x05, 0xf8, 0x02, 0xd8, 0xe1, 0x95, 0x0c, 0xae, 0x3e, 0x97, 0x93, 0xd9, 0x6b, 0x58, 0x6b,
	0x54, 0x8d, 0xeb, 0x6c, 0x75, 0x77, 0x46, 0xe3, 0x97, 0xc1, 0xed, 0xf2, 0x82, 0x26, 0x4b, 0xeb,
	0x61, 0xff, 0x9b, 0x03, 0x0f, 0x5a, 0x33, 0x4c, 0x8e, 0x99, 0x51, 0xf7, 0x3a, 0x84, 0x8d, 0xa1,
	0xcf, 0x95, 0x29, 0x12, 0xeb, 0x76, 0xb6, 0x9c, 0x9d, 0xd1, 0xd8, 0x0b, 0x2a, 0x3b, 0x82, 0x85,
	0x1d, 0xc1, 0x04, 0x31, 0x79, 0x2f, 0x92, 0x42, 0xf1, 0xba, 0x93, 0x3d, 0x84, 0x95, 0x23, 0xad,
	0x51, 0xbb, 0xdd, 0x2d, 0x67, 0x67, 0xc8, 0xab, 0x83, 0xff, 0xb3, 0x03, 0xa3, 0x06, 0x35, 0x63,
	0xd0, 0xcb, 0x44, 0xaa, 0x5c, 0x87, 0x9a, 0xe8, 0x3f, 0x5b, 0x87, 0x4e, 0x3c, 0xa3, 0x49, 0x43,
	0xde, 0x89, 0x67, 0xec, 0x29, 0x0c, 0x33, 0xb4, 0x13, 0x35, 0x47, 0xad, 0x88, 0xad, 0xcb, 0xaf,
	0x0a, 0xcc, 0x83, 0x41, 0x86, 0xf6, 0x60, 0x6e, 0x95, 0x76, 0x7b, 0x04, 0x5e, 0x9e, 0xd9, 0x0b,
	0x18, 0x35, 0x5e, 0x03, 0x77, 0xa5, 0xa4, 0x9c, 0xf4, 0xbe, 0xfc, 0x70, 0x1d, 0xde, 0x04, 0xd8,
	0x36, 0xf4, 0x8d, 0x15, 0xb6, 0x30, 0x6e, 0x9f, 0xf6, 0x1b, 0x91, 0x4d, 0x53, 0x2a, 0xf1, 0x1a,
	0x2a, 0x65, 0x44, 0x1a, 0x8b, 0xfc, 0x4d, 0xa9, 0x77, 0x95, 0xd4, 0x5d, 0x15, 0x4a, 0xf4, 0x4c,
	0x14, 0x89, 0x25, 0x74, 0x50, 0xa1, 0x97, 0x05, 0xe6, 0xc3, 0x5a, 0x82, 0x52, 0xd8, 0x18, 0x33,
	0x6a, 0x18, 0x52, 0x43, 0xab, 0xc6, 0x9e, 0x41, 0xcf, 0x8a, 0xc8, 0xb8, 0x40, 0x12, 0x86, 0x24,
	0xe1, 0xad, 0x88, 0x0c, 0xa7, 0xb2, 0xff, 0x01, 0xe0, 0x70, 0xca, 0x17, 0xef, 0xd0, 0x2b, 0xe8,
	0x1d, 0x4e, 0xf9, 0x22, 0xd6, 0xfd, 0x25, 0x63, 0x9d, 0xc6, 0x51, 0x16, 0x67, 0x51, 0x4d, 0xc2,
	0x89, 0xc2, 0xff, 0xde, 0x81, 0xc7, 0xb7, 0xf6, 0xdc, 0x18, 0xd0, 0x26, 0x74, 0xa5, 0xd1, 0x55,
	0x42, 0xb5, 0x9d, 0x65, 0x81, 0xed, 0xc2, 0x3a, 0x26, 0xb3, 0x06, 0x57, 0x95, 0x7d, 0xdd, 0x72,
	0x0d, 0x6b, 0x98, 0xde, 0xbb, 0xdd, 0xf4, 0x4d, 0xe8, 0x4b, 0x41, 0x96, 0x51, 0x78, 0xbc, 0x3e,
	0xb5, 0xc3, 0xe8, 0xdf, 0x19, 0xc6, 0xea, 0xdf, 0xc2, 0x18, 0xdc, 0x10, 0x86, 0x07, 0x83, 0x33,
	0x91, 0xc4, 0xb3, 0xd8, 0x5e, 0x50, 0x58, 0x5d, 0x7e, 0x79, 0xf6, 0xbf, 0x3a, 0xb0, 0xc1, 0x55,
	0xa6, 0xce, 0x29, 0x8f, 0xfa, 0x7b, 0x3b, 0xae, 0x3c, 0x71, 0x68, 0x95, 0x7f, 0xcc, 0x83, 0x4c,
	0xbc, 0xb7, 0x6f, 0x6d, 0xfc, 0xcb, 0x81, 0x8d, 0xc6, 0xb0, 0x83, 0x52, 0x06, 0x7b, 0x07, 0xa3,
	0x63, 0x65, 0x17, 0xf2, 0xd9, 0xe6, 0x1f, 0xec, 0x47, 0xe5, 0xc5, 0xe6, 0xed, 0xde, 0xb5, 0xc1,
	0xf5, 0xe5, 0xfd, 0xff, 0xd8, 0x19, 0xfc, 0xcf, 0xd1, 0x0a, 0xab, 0x9a, 0x09, 0x07, 0xcb, 0xde,
	0x36, 0xd5, 0xfe, 0x5e, 0xb8, 0x74, 0xff, 0x62, 0xee, 0x64, 0xff, 0xe3, 0x5e, 0x14, 0xdb, 0x4f,
	0xc5, 0x69, 0x20, 0x31, 0x0d, 0xd3, 0x58, 0x6a, 0x34, 0x38, 0xb7, 0x61, 0x8a, 0x32, 0xd4, 0xb9,
	0x0c, 0x5b, 0x64, 0xe1, 0x82, 0xec, 0xb4, 0x4f, 0xeb, 0xee, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x52, 0xb9, 0xf1, 0x31, 0x38, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CertificateAgentClient is the client API for CertificateAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CertificateAgentClient interface {
	GetRenewCSR(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RenewCSRResponse, error)
	RotateCertificate(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
}

type certificateAgentClient struct {
	cc *grpc.ClientConn
}

func NewCertificateAgentClient(cc *grpc.ClientConn) CertificateAgentClient {
	return &certificateAgentClient{cc}
}

func (c *certificateAgentClient) GetRenewCSR(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RenewCSRResponse, error) {
	out := new(RenewCSRResponse)
	err := c.cc.Invoke(ctx, "/moc.mocguestagent.security.CertificateAgent/GetRenewCSR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateAgentClient) RotateCertificate(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, "/moc.mocguestagent.security.CertificateAgent/RotateCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateAgentServer is the server API for CertificateAgent service.
type CertificateAgentServer interface {
	GetRenewCSR(context.Context, *empty.Empty) (*RenewCSRResponse, error)
	RotateCertificate(context.Context, *CertificateRequest) (*CertificateResponse, error)
}

// UnimplementedCertificateAgentServer can be embedded to have forward compatible implementations.
type UnimplementedCertificateAgentServer struct {
}

func (*UnimplementedCertificateAgentServer) GetRenewCSR(ctx context.Context, req *empty.Empty) (*RenewCSRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRenewCSR not implemented")
}
func (*UnimplementedCertificateAgentServer) RotateCertificate(ctx context.Context, req *CertificateRequest) (*CertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateCertificate not implemented")
}

func RegisterCertificateAgentServer(s *grpc.Server, srv CertificateAgentServer) {
	s.RegisterService(&_CertificateAgent_serviceDesc, srv)
}

func _CertificateAgent_GetRenewCSR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateAgentServer).GetRenewCSR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.mocguestagent.security.CertificateAgent/GetRenewCSR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateAgentServer).GetRenewCSR(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateAgent_RotateCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateAgentServer).RotateCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.mocguestagent.security.CertificateAgent/RotateCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateAgentServer).RotateCertificate(ctx, req.(*CertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CertificateAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.mocguestagent.security.CertificateAgent",
	HandlerType: (*CertificateAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRenewCSR",
			Handler:    _CertificateAgent_GetRenewCSR_Handler,
		},
		{
			MethodName: "RotateCertificate",
			Handler:    _CertificateAgent_RotateCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_mocguestagent_certificate.proto",
}
