// Code generated by protoc-gen-go. DO NOT EDIT.
// source: virtualmachine/moc_hypervguestagent_virtualmachine.proto

package compute

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VirtualMachineRunCommandRequest struct {
	Source                    *common.VirtualMachineRunCommandScriptSource     `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	RunCommandInputParameters []*common.VirtualMachineRunCommandInputParameter `protobuf:"bytes,3,rep,name=RunCommandInputParameters,proto3" json:"RunCommandInputParameters,omitempty"`
	RunAsUser                 string                                           `protobuf:"bytes,4,opt,name=RunAsUser,proto3" json:"RunAsUser,omitempty"`
	RunAsPassword             string                                           `protobuf:"bytes,5,opt,name=RunAsPassword,proto3" json:"RunAsPassword,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                         `json:"-"`
	XXX_unrecognized          []byte                                           `json:"-"`
	XXX_sizecache             int32                                            `json:"-"`
}

func (m *VirtualMachineRunCommandRequest) Reset()         { *m = VirtualMachineRunCommandRequest{} }
func (m *VirtualMachineRunCommandRequest) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandRequest) ProtoMessage()    {}
func (*VirtualMachineRunCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2548e2efde402ac2, []int{0}
}

func (m *VirtualMachineRunCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandRequest.Merge(m, src)
}
func (m *VirtualMachineRunCommandRequest) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Size(m)
}
func (m *VirtualMachineRunCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandRequest proto.InternalMessageInfo

func (m *VirtualMachineRunCommandRequest) GetSource() *common.VirtualMachineRunCommandScriptSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetRunCommandInputParameters() []*common.VirtualMachineRunCommandInputParameter {
	if m != nil {
		return m.RunCommandInputParameters
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetRunAsUser() string {
	if m != nil {
		return m.RunAsUser
	}
	return ""
}

func (m *VirtualMachineRunCommandRequest) GetRunAsPassword() string {
	if m != nil {
		return m.RunAsPassword
	}
	return ""
}

type VirtualMachineRunCommandResponse struct {
	InstanceView         *common.VirtualMachineRunCommandInstanceView `protobuf:"bytes,2,opt,name=InstanceView,proto3" json:"InstanceView,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *VirtualMachineRunCommandResponse) Reset()         { *m = VirtualMachineRunCommandResponse{} }
func (m *VirtualMachineRunCommandResponse) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandResponse) ProtoMessage()    {}
func (*VirtualMachineRunCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2548e2efde402ac2, []int{1}
}

func (m *VirtualMachineRunCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandResponse.Merge(m, src)
}
func (m *VirtualMachineRunCommandResponse) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Size(m)
}
func (m *VirtualMachineRunCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandResponse proto.InternalMessageInfo

func (m *VirtualMachineRunCommandResponse) GetInstanceView() *common.VirtualMachineRunCommandInstanceView {
	if m != nil {
		return m.InstanceView
	}
	return nil
}

func init() {
	proto.RegisterType((*VirtualMachineRunCommandRequest)(nil), "moc.hypervguestagent.compute.VirtualMachineRunCommandRequest")
	proto.RegisterType((*VirtualMachineRunCommandResponse)(nil), "moc.hypervguestagent.compute.VirtualMachineRunCommandResponse")
}

func init() {
	proto.RegisterFile("virtualmachine/moc_hypervguestagent_virtualmachine.proto", fileDescriptor_2548e2efde402ac2)
}

var fileDescriptor_2548e2efde402ac2 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcb, 0x6e, 0xd4, 0x30,
	0x18, 0x85, 0x49, 0x5b, 0x2a, 0xd5, 0x85, 0x05, 0x46, 0x82, 0x74, 0xb8, 0x8d, 0xb2, 0x1a, 0x40,
	0x72, 0xa4, 0x41, 0x08, 0x36, 0x20, 0x4d, 0x2b, 0x24, 0xba, 0x28, 0xaa, 0x52, 0xd1, 0x05, 0x9b,
	0xca, 0xe3, 0xfe, 0x93, 0x58, 0xd4, 0xfe, 0x5d, 0x5f, 0x5a, 0xf5, 0x0d, 0xd8, 0xf0, 0x0c, 0x3c,
	0x05, 0xcf, 0xc5, 0x2b, 0x20, 0xe7, 0xa2, 0x49, 0x2a, 0x4d, 0x41, 0x5d, 0x45, 0xc9, 0x39, 0xdf,
	0xef, 0x63, 0xe7, 0x98, 0xbc, 0xbf, 0x90, 0xd6, 0x07, 0x7e, 0xa6, 0xb8, 0xa8, 0xa4, 0x86, 0x5c,
	0xa1, 0x38, 0xa9, 0xae, 0x0c, 0xd8, 0x8b, 0x32, 0x80, 0xf3, 0xbc, 0x04, 0xed, 0x4f, 0x86, 0x1e,
	0x66, 0x2c, 0x7a, 0xa4, 0x4f, 0x15, 0x0a, 0x76, 0xdd, 0xca, 0x04, 0x2a, 0x13, 0x3c, 0x8c, 0x9e,
	0x94, 0x88, 0xe5, 0x19, 0xe4, 0xb5, 0x77, 0x1e, 0x16, 0x39, 0x28, 0xe3, 0xaf, 0x1a, 0x74, 0xf4,
	0x38, 0xae, 0x22, 0x50, 0x29, 0xd4, 0xed, 0xa3, 0x15, 0x9e, 0x0f, 0x85, 0x38, 0x69, 0xa0, 0x3f,
	0xeb, 0xe9, 0x1a, 0xbd, 0x5c, 0x48, 0xc1, 0xbd, 0xec, 0xe4, 0xec, 0xd7, 0x1a, 0x79, 0x71, 0xdc,
	0x64, 0x3d, 0x68, 0xb2, 0x16, 0x41, 0xef, 0xa1, 0x52, 0x5c, 0x9f, 0x16, 0x70, 0x1e, 0x53, 0xd2,
	0x19, 0xd9, 0x3c, 0xc2, 0x60, 0x05, 0xa4, 0x6b, 0xe3, 0x64, 0xb2, 0x3d, 0x7d, 0xc9, 0xe2, 0x3e,
	0x56, 0x51, 0x47, 0xc2, 0x4a, 0xe3, 0x1b, 0xa0, 0x68, 0x41, 0x2a, 0xc9, 0xce, 0xd2, 0xb1, 0xaf,
	0x4d, 0xf0, 0x87, 0xdc, 0x72, 0x05, 0x1e, 0xac, 0x4b, 0xd7, 0xc7, 0xeb, 0x93, 0xed, 0xe9, 0xeb,
	0x1b, 0xa7, 0x0e, 0x99, 0x62, 0xf5, 0x34, 0x9a, 0x91, 0xad, 0x22, 0xe8, 0x99, 0xfb, 0xea, 0xc0,
	0xa6, 0x1b, 0xe3, 0x64, 0xb2, 0xb5, 0xbb, 0xf1, 0xe3, 0x77, 0x9a, 0x14, 0xcb, 0xcf, 0xf4, 0x15,
	0xb9, 0x5f, 0xbf, 0x1c, 0x72, 0xe7, 0x2e, 0xd1, 0x9e, 0xa6, 0x77, 0x7b, 0xbe, 0xa1, 0x94, 0x9d,
	0x93, 0xf1, 0xea, 0x03, 0x72, 0x06, 0xb5, 0x03, 0x7a, 0x40, 0xee, 0xed, 0x6b, 0xe7, 0xb9, 0x16,
	0x70, 0x2c, 0xe1, 0xf2, 0xbf, 0xce, 0xa9, 0x0f, 0x14, 0x03, 0x7c, 0xfa, 0x27, 0x21, 0x0f, 0x87,
	0xd8, 0x2c, 0x36, 0x85, 0x7e, 0x26, 0x0f, 0xf6, 0x2a, 0x10, 0xdf, 0xbf, 0xf4, 0xfe, 0x23, 0x7d,
	0xc4, 0x9a, 0xde, 0xb0, 0xae, 0x37, 0xec, 0x53, 0xec, 0xcd, 0x68, 0xa7, 0x5e, 0xbd, 0x6f, 0xed,
	0xe2, 0x66, 0x77, 0xe8, 0xcf, 0x84, 0x90, 0x65, 0x14, 0xfa, 0x81, 0xdd, 0xd4, 0x4c, 0xf6, 0x8f,
	0x82, 0x8c, 0x3e, 0xde, 0x16, 0xef, 0xf2, 0xec, 0xbe, 0xfb, 0xf6, 0xb6, 0x94, 0xbe, 0x0a, 0xf3,
	0x08, 0xe5, 0x4a, 0x0a, 0x8b, 0x0e, 0x17, 0x3e, 0xde, 0xad, 0xdc, 0x1a, 0x91, 0x5f, 0x9f, 0x9d,
	0xb7, 0xb3, 0xe7, 0x9b, 0xf5, 0xae, 0xdf, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x3a, 0x7f,
	0x2d, 0x95, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VirtualMachineAgentClient is the client API for VirtualMachineAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtualMachineAgentClient interface {
	CheckNotification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.NotificationResponse, error)
	RunCommand(ctx context.Context, in *VirtualMachineRunCommandRequest, opts ...grpc.CallOption) (*VirtualMachineRunCommandResponse, error)
}

type virtualMachineAgentClient struct {
	cc *grpc.ClientConn
}

func NewVirtualMachineAgentClient(cc *grpc.ClientConn) VirtualMachineAgentClient {
	return &virtualMachineAgentClient{cc}
}

func (c *virtualMachineAgentClient) CheckNotification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.NotificationResponse, error) {
	out := new(common.NotificationResponse)
	err := c.cc.Invoke(ctx, "/moc.hypervguestagent.compute.VirtualMachineAgent/CheckNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) RunCommand(ctx context.Context, in *VirtualMachineRunCommandRequest, opts ...grpc.CallOption) (*VirtualMachineRunCommandResponse, error) {
	out := new(VirtualMachineRunCommandResponse)
	err := c.cc.Invoke(ctx, "/moc.hypervguestagent.compute.VirtualMachineAgent/RunCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualMachineAgentServer is the server API for VirtualMachineAgent service.
type VirtualMachineAgentServer interface {
	CheckNotification(context.Context, *empty.Empty) (*common.NotificationResponse, error)
	RunCommand(context.Context, *VirtualMachineRunCommandRequest) (*VirtualMachineRunCommandResponse, error)
}

// UnimplementedVirtualMachineAgentServer can be embedded to have forward compatible implementations.
type UnimplementedVirtualMachineAgentServer struct {
}

func (*UnimplementedVirtualMachineAgentServer) CheckNotification(ctx context.Context, req *empty.Empty) (*common.NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNotification not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) RunCommand(ctx context.Context, req *VirtualMachineRunCommandRequest) (*VirtualMachineRunCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCommand not implemented")
}

func RegisterVirtualMachineAgentServer(s *grpc.Server, srv VirtualMachineAgentServer) {
	s.RegisterService(&_VirtualMachineAgent_serviceDesc, srv)
}

func _VirtualMachineAgent_CheckNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).CheckNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.hypervguestagent.compute.VirtualMachineAgent/CheckNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).CheckNotification(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachineRunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.hypervguestagent.compute.VirtualMachineAgent/RunCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).RunCommand(ctx, req.(*VirtualMachineRunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VirtualMachineAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.hypervguestagent.compute.VirtualMachineAgent",
	HandlerType: (*VirtualMachineAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckNotification",
			Handler:    _VirtualMachineAgent_CheckNotification_Handler,
		},
		{
			MethodName: "RunCommand",
			Handler:    _VirtualMachineAgent_RunCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "virtualmachine/moc_hypervguestagent_virtualmachine.proto",
}
