// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_nodeagent_host.proto

package node

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HostState int32

const (
	HostState_Unknown  HostState = 0
	HostState_Active   HostState = 1
	HostState_Inactive HostState = 2
	HostState_Poweroff HostState = 3
)

var HostState_name = map[int32]string{
	0: "Unknown",
	1: "Active",
	2: "Inactive",
	3: "Poweroff",
}

var HostState_value = map[string]int32{
	"Unknown":  0,
	"Active":   1,
	"Inactive": 2,
	"Poweroff": 3,
}

func (x HostState) String() string {
	return proto.EnumName(HostState_name, int32(x))
}

func (HostState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_118548269615dab7, []int{0}
}

type HostRequest struct {
	Hosts                []*Host          `protobuf:"bytes,1,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
	OperationType        common.Operation `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HostRequest) Reset()         { *m = HostRequest{} }
func (m *HostRequest) String() string { return proto.CompactTextString(m) }
func (*HostRequest) ProtoMessage()    {}
func (*HostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_118548269615dab7, []int{0}
}

func (m *HostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostRequest.Unmarshal(m, b)
}
func (m *HostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostRequest.Marshal(b, m, deterministic)
}
func (m *HostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostRequest.Merge(m, src)
}
func (m *HostRequest) XXX_Size() int {
	return xxx_messageInfo_HostRequest.Size(m)
}
func (m *HostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostRequest proto.InternalMessageInfo

func (m *HostRequest) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *HostRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type HostResponse struct {
	Hosts                []*Host             `protobuf:"bytes,1,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HostResponse) Reset()         { *m = HostResponse{} }
func (m *HostResponse) String() string { return proto.CompactTextString(m) }
func (*HostResponse) ProtoMessage()    {}
func (*HostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_118548269615dab7, []int{1}
}

func (m *HostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostResponse.Unmarshal(m, b)
}
func (m *HostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostResponse.Marshal(b, m, deterministic)
}
func (m *HostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostResponse.Merge(m, src)
}
func (m *HostResponse) XXX_Size() int {
	return xxx_messageInfo_HostResponse.Size(m)
}
func (m *HostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HostResponse proto.InternalMessageInfo

func (m *HostResponse) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *HostResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *HostResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Host struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Fqdn                 string         `protobuf:"bytes,3,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	Status               *common.Status `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LocationName         string         `protobuf:"bytes,5,opt,name=locationName,proto3" json:"locationName,omitempty"`
	Certificate          string         `protobuf:"bytes,6,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Port                 int32          `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	AuthorizerPort       int32          `protobuf:"varint,8,opt,name=authorizerPort,proto3" json:"authorizerPort,omitempty"`
	RunningState         HostState      `protobuf:"varint,9,opt,name=runningState,proto3,enum=moc.nodeagent.host.HostState" json:"runningState,omitempty"`
	Tags                 *common.Tags   `protobuf:"bytes,10,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_118548269615dab7, []int{2}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Host) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

func (m *Host) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Host) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

func (m *Host) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *Host) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Host) GetAuthorizerPort() int32 {
	if m != nil {
		return m.AuthorizerPort
	}
	return 0
}

func (m *Host) GetRunningState() HostState {
	if m != nil {
		return m.RunningState
	}
	return HostState_Unknown
}

func (m *Host) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterEnum("moc.nodeagent.host.HostState", HostState_name, HostState_value)
	proto.RegisterType((*HostRequest)(nil), "moc.nodeagent.host.HostRequest")
	proto.RegisterType((*HostResponse)(nil), "moc.nodeagent.host.HostResponse")
	proto.RegisterType((*Host)(nil), "moc.nodeagent.host.Host")
}

func init() { proto.RegisterFile("moc_nodeagent_host.proto", fileDescriptor_118548269615dab7) }

var fileDescriptor_118548269615dab7 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xe1, 0x6a, 0x13, 0x41,
	0x10, 0xee, 0xa5, 0xc9, 0xb5, 0x99, 0x4b, 0x43, 0x59, 0x04, 0x97, 0x40, 0x35, 0x44, 0x28, 0x41,
	0xf1, 0x0e, 0xa2, 0x0f, 0x60, 0x02, 0x82, 0xfd, 0xa1, 0x96, 0xb3, 0x2a, 0xf8, 0xc3, 0xb2, 0xd9,
	0xec, 0x5d, 0x8e, 0xe6, 0x76, 0xae, 0xbb, 0x7b, 0x0d, 0xfa, 0x04, 0x7d, 0x21, 0x1f, 0xc3, 0x77,
	0x92, 0x9d, 0x8b, 0xc1, 0x28, 0xf9, 0xe1, 0xaf, 0x9b, 0x99, 0xef, 0xfb, 0xe6, 0x9b, 0xd9, 0x1b,
	0xe0, 0x25, 0xca, 0x6b, 0x8d, 0x0b, 0x25, 0x72, 0xa5, 0xdd, 0xf5, 0x12, 0xad, 0x8b, 0x2b, 0x83,
	0x0e, 0x19, 0x2b, 0x51, 0xc6, 0x5b, 0x24, 0xf6, 0xc8, 0xe0, 0x51, 0x8e, 0x98, 0xaf, 0x54, 0x42,
	0x8c, 0x79, 0x9d, 0x25, 0x6b, 0x23, 0xaa, 0x4a, 0x19, 0xdb, 0x68, 0x06, 0x0f, 0x7d, 0x37, 0x89,
	0x65, 0x89, 0x7a, 0xf3, 0x69, 0x80, 0x91, 0x85, 0xe8, 0x0d, 0x5a, 0x97, 0xaa, 0xdb, 0x5a, 0x59,
	0xc7, 0x62, 0xe8, 0xf8, 0xd4, 0xf2, 0x60, 0x78, 0x38, 0x8e, 0x26, 0x3c, 0xfe, 0xd7, 0x2b, 0x26,
	0x7e, 0x43, 0x63, 0x2f, 0xe1, 0xe4, 0x7d, 0xa5, 0x8c, 0x70, 0x05, 0xea, 0xab, 0x6f, 0x95, 0xe2,
	0xad, 0x61, 0x30, 0xee, 0x4f, 0xfa, 0xa4, 0xdb, 0x22, 0xe9, 0x2e, 0x69, 0x74, 0x1f, 0x40, 0xaf,
	0x71, 0xb5, 0x15, 0x6a, 0xab, 0xfe, 0xdb, 0x76, 0x02, 0x61, 0xaa, 0x6c, 0xbd, 0x72, 0xe4, 0x17,
	0x4d, 0x06, 0x71, 0xb3, 0x7f, 0xfc, 0x7b, 0xff, 0x78, 0x86, 0xb8, 0xfa, 0x24, 0x56, 0xb5, 0x4a,
	0x37, 0x4c, 0xf6, 0x00, 0x3a, 0xaf, 0x8d, 0x41, 0xc3, 0x0f, 0x87, 0xc1, 0xb8, 0x9b, 0x36, 0xc9,
	0xe8, 0x67, 0x0b, 0xda, 0xbe, 0x27, 0x63, 0xd0, 0xd6, 0xa2, 0x54, 0x3c, 0x20, 0x94, 0x62, 0xd6,
	0x87, 0x56, 0xb1, 0x20, 0x8b, 0x6e, 0xda, 0x2a, 0x16, 0x9e, 0x93, 0xdd, 0x2e, 0xf4, 0xa6, 0x03,
	0xc5, 0xec, 0x09, 0x84, 0xd6, 0x09, 0x57, 0x5b, 0xde, 0xa6, 0x51, 0x22, 0x9a, 0xfd, 0x03, 0x95,
	0xd2, 0x0d, 0xc4, 0x46, 0xd0, 0x5b, 0xa1, 0xa4, 0x07, 0x78, 0xe7, 0x4d, 0x3a, 0xd4, 0x60, 0xa7,
	0xc6, 0xce, 0x21, 0x92, 0xca, 0xb8, 0x22, 0x2b, 0xa4, 0x70, 0x8a, 0x87, 0x9e, 0x32, 0x6b, 0xdf,
	0xff, 0xe0, 0x41, 0xfa, 0x27, 0xe0, 0x87, 0xa8, 0xd0, 0x38, 0x7e, 0x34, 0x0c, 0xc6, 0x9d, 0x94,
	0x62, 0x76, 0x0e, 0x7d, 0x51, 0xbb, 0x25, 0x9a, 0xe2, 0xbb, 0x32, 0x97, 0x1e, 0x3d, 0x26, 0xf4,
	0xaf, 0x2a, 0x9b, 0x42, 0xcf, 0xd4, 0x5a, 0x17, 0x3a, 0xf7, 0x03, 0x2a, 0xde, 0xa5, 0xbf, 0x75,
	0xb6, 0xef, 0xb9, 0x89, 0x94, 0xee, 0x48, 0xd8, 0x19, 0xb4, 0x9d, 0xc8, 0x2d, 0x07, 0xda, 0xb6,
	0x4b, 0xd2, 0x2b, 0x91, 0xdb, 0x94, 0xca, 0x4f, 0x5f, 0x41, 0x77, 0xab, 0x64, 0x11, 0x1c, 0x7d,
	0xd4, 0x37, 0x1a, 0xd7, 0xfa, 0xf4, 0x80, 0x01, 0x84, 0x53, 0xe9, 0x8a, 0x3b, 0x75, 0x1a, 0xb0,
	0x1e, 0x1c, 0x5f, 0x68, 0xd1, 0x64, 0x2d, 0x9f, 0x5d, 0xe2, 0x5a, 0x19, 0xcc, 0xb2, 0xd3, 0xc3,
	0xc9, 0x57, 0x38, 0xf9, 0x6c, 0xed, 0xc2, 0x77, 0x99, 0xfa, 0x71, 0xd8, 0x5b, 0x08, 0x2f, 0xf4,
	0x1d, 0xde, 0x28, 0xf6, 0x78, 0xef, 0x5d, 0x34, 0xe7, 0x3b, 0x18, 0xee, 0x27, 0x34, 0x97, 0x36,
	0x3a, 0x98, 0x3d, 0xff, 0xf2, 0x2c, 0x2f, 0xdc, 0xb2, 0x9e, 0xc7, 0x12, 0xcb, 0xa4, 0x2c, 0xa4,
	0x41, 0x8b, 0x99, 0x4b, 0x4a, 0x94, 0x89, 0xa9, 0x64, 0xb2, 0x55, 0x53, 0x34, 0x0f, 0xe9, 0xa4,
	0x5e, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x75, 0xa0, 0xf2, 0x62, 0x90, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WssdHostAgentClient is the client API for WssdHostAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WssdHostAgentClient interface {
	Invoke(ctx context.Context, in *HostRequest, opts ...grpc.CallOption) (*HostResponse, error)
}

type wssdHostAgentClient struct {
	cc *grpc.ClientConn
}

func NewWssdHostAgentClient(cc *grpc.ClientConn) WssdHostAgentClient {
	return &wssdHostAgentClient{cc}
}

func (c *wssdHostAgentClient) Invoke(ctx context.Context, in *HostRequest, opts ...grpc.CallOption) (*HostResponse, error) {
	out := new(HostResponse)
	err := c.cc.Invoke(ctx, "/moc.nodeagent.host.WssdHostAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WssdHostAgentServer is the server API for WssdHostAgent service.
type WssdHostAgentServer interface {
	Invoke(context.Context, *HostRequest) (*HostResponse, error)
}

// UnimplementedWssdHostAgentServer can be embedded to have forward compatible implementations.
type UnimplementedWssdHostAgentServer struct {
}

func (*UnimplementedWssdHostAgentServer) Invoke(ctx context.Context, req *HostRequest) (*HostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterWssdHostAgentServer(s *grpc.Server, srv WssdHostAgentServer) {
	s.RegisterService(&_WssdHostAgent_serviceDesc, srv)
}

func _WssdHostAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WssdHostAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.nodeagent.host.WssdHostAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WssdHostAgentServer).Invoke(ctx, req.(*HostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WssdHostAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.nodeagent.host.WssdHostAgent",
	HandlerType: (*WssdHostAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _WssdHostAgent_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_nodeagent_host.proto",
}
