// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_mochostagent_virtualmachine.proto

package compute

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterVirtualMachineRequest struct {
	VirtualMachine       *VirtualMachine `protobuf:"bytes,1,opt,name=VirtualMachine,proto3" json:"VirtualMachine,omitempty"`
	WaitForConnection    bool            `protobuf:"varint,2,opt,name=waitForConnection,proto3" json:"waitForConnection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RegisterVirtualMachineRequest) Reset()         { *m = RegisterVirtualMachineRequest{} }
func (m *RegisterVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterVirtualMachineRequest) ProtoMessage()    {}
func (*RegisterVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{0}
}

func (m *RegisterVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterVirtualMachineRequest.Unmarshal(m, b)
}
func (m *RegisterVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (m *RegisterVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterVirtualMachineRequest.Merge(m, src)
}
func (m *RegisterVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterVirtualMachineRequest.Size(m)
}
func (m *RegisterVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterVirtualMachineRequest proto.InternalMessageInfo

func (m *RegisterVirtualMachineRequest) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

func (m *RegisterVirtualMachineRequest) GetWaitForConnection() bool {
	if m != nil {
		return m.WaitForConnection
	}
	return false
}

type RegisterVirtualMachineInstanceView struct {
	Output               string   `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterVirtualMachineInstanceView) Reset()         { *m = RegisterVirtualMachineInstanceView{} }
func (m *RegisterVirtualMachineInstanceView) String() string { return proto.CompactTextString(m) }
func (*RegisterVirtualMachineInstanceView) ProtoMessage()    {}
func (*RegisterVirtualMachineInstanceView) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{1}
}

func (m *RegisterVirtualMachineInstanceView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterVirtualMachineInstanceView.Unmarshal(m, b)
}
func (m *RegisterVirtualMachineInstanceView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterVirtualMachineInstanceView.Marshal(b, m, deterministic)
}
func (m *RegisterVirtualMachineInstanceView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterVirtualMachineInstanceView.Merge(m, src)
}
func (m *RegisterVirtualMachineInstanceView) XXX_Size() int {
	return xxx_messageInfo_RegisterVirtualMachineInstanceView.Size(m)
}
func (m *RegisterVirtualMachineInstanceView) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterVirtualMachineInstanceView.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterVirtualMachineInstanceView proto.InternalMessageInfo

func (m *RegisterVirtualMachineInstanceView) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *RegisterVirtualMachineInstanceView) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RegisterVirtualMachineResponse struct {
	InstanceView         *RegisterVirtualMachineInstanceView `protobuf:"bytes,1,opt,name=InstanceView,proto3" json:"InstanceView,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *RegisterVirtualMachineResponse) Reset()         { *m = RegisterVirtualMachineResponse{} }
func (m *RegisterVirtualMachineResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterVirtualMachineResponse) ProtoMessage()    {}
func (*RegisterVirtualMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{2}
}

func (m *RegisterVirtualMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterVirtualMachineResponse.Unmarshal(m, b)
}
func (m *RegisterVirtualMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterVirtualMachineResponse.Marshal(b, m, deterministic)
}
func (m *RegisterVirtualMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterVirtualMachineResponse.Merge(m, src)
}
func (m *RegisterVirtualMachineResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterVirtualMachineResponse.Size(m)
}
func (m *RegisterVirtualMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterVirtualMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterVirtualMachineResponse proto.InternalMessageInfo

func (m *RegisterVirtualMachineResponse) GetInstanceView() *RegisterVirtualMachineInstanceView {
	if m != nil {
		return m.InstanceView
	}
	return nil
}

type DeregisterVirtualMachineRequest struct {
	VirtualMachineId     string   `protobuf:"bytes,1,opt,name=VirtualMachineId,proto3" json:"VirtualMachineId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeregisterVirtualMachineRequest) Reset()         { *m = DeregisterVirtualMachineRequest{} }
func (m *DeregisterVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*DeregisterVirtualMachineRequest) ProtoMessage()    {}
func (*DeregisterVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{3}
}

func (m *DeregisterVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterVirtualMachineRequest.Unmarshal(m, b)
}
func (m *DeregisterVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (m *DeregisterVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterVirtualMachineRequest.Merge(m, src)
}
func (m *DeregisterVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_DeregisterVirtualMachineRequest.Size(m)
}
func (m *DeregisterVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterVirtualMachineRequest proto.InternalMessageInfo

func (m *DeregisterVirtualMachineRequest) GetVirtualMachineId() string {
	if m != nil {
		return m.VirtualMachineId
	}
	return ""
}

type DeregisterVirtualMachineInstanceView struct {
	Output               string   `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeregisterVirtualMachineInstanceView) Reset()         { *m = DeregisterVirtualMachineInstanceView{} }
func (m *DeregisterVirtualMachineInstanceView) String() string { return proto.CompactTextString(m) }
func (*DeregisterVirtualMachineInstanceView) ProtoMessage()    {}
func (*DeregisterVirtualMachineInstanceView) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{4}
}

func (m *DeregisterVirtualMachineInstanceView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterVirtualMachineInstanceView.Unmarshal(m, b)
}
func (m *DeregisterVirtualMachineInstanceView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterVirtualMachineInstanceView.Marshal(b, m, deterministic)
}
func (m *DeregisterVirtualMachineInstanceView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterVirtualMachineInstanceView.Merge(m, src)
}
func (m *DeregisterVirtualMachineInstanceView) XXX_Size() int {
	return xxx_messageInfo_DeregisterVirtualMachineInstanceView.Size(m)
}
func (m *DeregisterVirtualMachineInstanceView) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterVirtualMachineInstanceView.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterVirtualMachineInstanceView proto.InternalMessageInfo

func (m *DeregisterVirtualMachineInstanceView) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *DeregisterVirtualMachineInstanceView) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeregisterVirtualMachineResponse struct {
	InstanceView         *DeregisterVirtualMachineInstanceView `protobuf:"bytes,1,opt,name=InstanceView,proto3" json:"InstanceView,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *DeregisterVirtualMachineResponse) Reset()         { *m = DeregisterVirtualMachineResponse{} }
func (m *DeregisterVirtualMachineResponse) String() string { return proto.CompactTextString(m) }
func (*DeregisterVirtualMachineResponse) ProtoMessage()    {}
func (*DeregisterVirtualMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{5}
}

func (m *DeregisterVirtualMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterVirtualMachineResponse.Unmarshal(m, b)
}
func (m *DeregisterVirtualMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterVirtualMachineResponse.Marshal(b, m, deterministic)
}
func (m *DeregisterVirtualMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterVirtualMachineResponse.Merge(m, src)
}
func (m *DeregisterVirtualMachineResponse) XXX_Size() int {
	return xxx_messageInfo_DeregisterVirtualMachineResponse.Size(m)
}
func (m *DeregisterVirtualMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterVirtualMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterVirtualMachineResponse proto.InternalMessageInfo

func (m *DeregisterVirtualMachineResponse) GetInstanceView() *DeregisterVirtualMachineInstanceView {
	if m != nil {
		return m.InstanceView
	}
	return nil
}

type OperatingSystemConfiguration struct {
	Ostype               common.OperatingSystemType `protobuf:"varint,1,opt,name=ostype,proto3,enum=moc.OperatingSystemType" json:"ostype,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *OperatingSystemConfiguration) Reset()         { *m = OperatingSystemConfiguration{} }
func (m *OperatingSystemConfiguration) String() string { return proto.CompactTextString(m) }
func (*OperatingSystemConfiguration) ProtoMessage()    {}
func (*OperatingSystemConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{6}
}

func (m *OperatingSystemConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatingSystemConfiguration.Unmarshal(m, b)
}
func (m *OperatingSystemConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatingSystemConfiguration.Marshal(b, m, deterministic)
}
func (m *OperatingSystemConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatingSystemConfiguration.Merge(m, src)
}
func (m *OperatingSystemConfiguration) XXX_Size() int {
	return xxx_messageInfo_OperatingSystemConfiguration.Size(m)
}
func (m *OperatingSystemConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatingSystemConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_OperatingSystemConfiguration proto.InternalMessageInfo

func (m *OperatingSystemConfiguration) GetOstype() common.OperatingSystemType {
	if m != nil {
		return m.Ostype
	}
	return common.OperatingSystemType_WINDOWS
}

type VirtualMachine struct {
	Name                   string                                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                     string                                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Os                     *OperatingSystemConfiguration           `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Entity                 *common.Entity                          `protobuf:"bytes,4,opt,name=entity,proto3" json:"entity,omitempty"`
	Tags                   *common.Tags                            `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	GuestAgentInstanceView *common.VirtualMachineAgentInstanceView `protobuf:"bytes,6,opt,name=guestAgentInstanceView,proto3" json:"guestAgentInstanceView,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                                `json:"-"`
	XXX_unrecognized       []byte                                  `json:"-"`
	XXX_sizecache          int32                                   `json:"-"`
}

func (m *VirtualMachine) Reset()         { *m = VirtualMachine{} }
func (m *VirtualMachine) String() string { return proto.CompactTextString(m) }
func (*VirtualMachine) ProtoMessage()    {}
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{7}
}

func (m *VirtualMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachine.Unmarshal(m, b)
}
func (m *VirtualMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachine.Marshal(b, m, deterministic)
}
func (m *VirtualMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachine.Merge(m, src)
}
func (m *VirtualMachine) XXX_Size() int {
	return xxx_messageInfo_VirtualMachine.Size(m)
}
func (m *VirtualMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachine.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachine proto.InternalMessageInfo

func (m *VirtualMachine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualMachine) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VirtualMachine) GetOs() *OperatingSystemConfiguration {
	if m != nil {
		return m.Os
	}
	return nil
}

func (m *VirtualMachine) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *VirtualMachine) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *VirtualMachine) GetGuestAgentInstanceView() *common.VirtualMachineAgentInstanceView {
	if m != nil {
		return m.GuestAgentInstanceView
	}
	return nil
}

type VirtualMachineRunCommandRequest struct {
	VirtualMachine            *VirtualMachine                                  `protobuf:"bytes,1,opt,name=VirtualMachine,proto3" json:"VirtualMachine,omitempty"`
	Source                    *common.VirtualMachineRunCommandScriptSource     `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	RunCommandInputParameters []*common.VirtualMachineRunCommandInputParameter `protobuf:"bytes,3,rep,name=RunCommandInputParameters,proto3" json:"RunCommandInputParameters,omitempty"`
	OperationID               string                                           `protobuf:"bytes,4,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	RunAsUser                 string                                           `protobuf:"bytes,5,opt,name=RunAsUser,proto3" json:"RunAsUser,omitempty"`
	RunAsPassword             string                                           `protobuf:"bytes,6,opt,name=RunAsPassword,proto3" json:"RunAsPassword,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                         `json:"-"`
	XXX_unrecognized          []byte                                           `json:"-"`
	XXX_sizecache             int32                                            `json:"-"`
}

func (m *VirtualMachineRunCommandRequest) Reset()         { *m = VirtualMachineRunCommandRequest{} }
func (m *VirtualMachineRunCommandRequest) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandRequest) ProtoMessage()    {}
func (*VirtualMachineRunCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{8}
}

func (m *VirtualMachineRunCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandRequest.Merge(m, src)
}
func (m *VirtualMachineRunCommandRequest) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Size(m)
}
func (m *VirtualMachineRunCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandRequest proto.InternalMessageInfo

func (m *VirtualMachineRunCommandRequest) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetSource() *common.VirtualMachineRunCommandScriptSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetRunCommandInputParameters() []*common.VirtualMachineRunCommandInputParameter {
	if m != nil {
		return m.RunCommandInputParameters
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetOperationID() string {
	if m != nil {
		return m.OperationID
	}
	return ""
}

func (m *VirtualMachineRunCommandRequest) GetRunAsUser() string {
	if m != nil {
		return m.RunAsUser
	}
	return ""
}

func (m *VirtualMachineRunCommandRequest) GetRunAsPassword() string {
	if m != nil {
		return m.RunAsPassword
	}
	return ""
}

type VirtualMachineRunCommandResponse struct {
	InstanceView         *common.VirtualMachineRunCommandInstanceView `protobuf:"bytes,1,opt,name=InstanceView,proto3" json:"InstanceView,omitempty"`
	OperationID          string                                       `protobuf:"bytes,2,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *VirtualMachineRunCommandResponse) Reset()         { *m = VirtualMachineRunCommandResponse{} }
func (m *VirtualMachineRunCommandResponse) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandResponse) ProtoMessage()    {}
func (*VirtualMachineRunCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{9}
}

func (m *VirtualMachineRunCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandResponse.Merge(m, src)
}
func (m *VirtualMachineRunCommandResponse) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Size(m)
}
func (m *VirtualMachineRunCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandResponse proto.InternalMessageInfo

func (m *VirtualMachineRunCommandResponse) GetInstanceView() *common.VirtualMachineRunCommandInstanceView {
	if m != nil {
		return m.InstanceView
	}
	return nil
}

func (m *VirtualMachineRunCommandResponse) GetOperationID() string {
	if m != nil {
		return m.OperationID
	}
	return ""
}

type GuestAgentInfoRequest struct {
	VirtualMachineId     string   `protobuf:"bytes,1,opt,name=VirtualMachineId,proto3" json:"VirtualMachineId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuestAgentInfoRequest) Reset()         { *m = GuestAgentInfoRequest{} }
func (m *GuestAgentInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GuestAgentInfoRequest) ProtoMessage()    {}
func (*GuestAgentInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{10}
}

func (m *GuestAgentInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestAgentInfoRequest.Unmarshal(m, b)
}
func (m *GuestAgentInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestAgentInfoRequest.Marshal(b, m, deterministic)
}
func (m *GuestAgentInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestAgentInfoRequest.Merge(m, src)
}
func (m *GuestAgentInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GuestAgentInfoRequest.Size(m)
}
func (m *GuestAgentInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestAgentInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GuestAgentInfoRequest proto.InternalMessageInfo

func (m *GuestAgentInfoRequest) GetVirtualMachineId() string {
	if m != nil {
		return m.VirtualMachineId
	}
	return ""
}

type GuestAgentInfoResponse struct {
	Version              *common.Version    `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	State                common.HealthState `protobuf:"varint,2,opt,name=State,proto3,enum=moc.HealthState" json:"State,omitempty"`
	Error                string             `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GuestAgentInfoResponse) Reset()         { *m = GuestAgentInfoResponse{} }
func (m *GuestAgentInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GuestAgentInfoResponse) ProtoMessage()    {}
func (*GuestAgentInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{11}
}

func (m *GuestAgentInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestAgentInfoResponse.Unmarshal(m, b)
}
func (m *GuestAgentInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestAgentInfoResponse.Marshal(b, m, deterministic)
}
func (m *GuestAgentInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestAgentInfoResponse.Merge(m, src)
}
func (m *GuestAgentInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GuestAgentInfoResponse.Size(m)
}
func (m *GuestAgentInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestAgentInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GuestAgentInfoResponse proto.InternalMessageInfo

func (m *GuestAgentInfoResponse) GetVersion() *common.Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *GuestAgentInfoResponse) GetState() common.HealthState {
	if m != nil {
		return m.State
	}
	return common.HealthState_NOTKNOWN
}

func (m *GuestAgentInfoResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type VirtualMachineRepairGuestAgentRequest struct {
	VirtualMachine       *VirtualMachine `protobuf:"bytes,1,opt,name=VirtualMachine,proto3" json:"VirtualMachine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VirtualMachineRepairGuestAgentRequest) Reset()         { *m = VirtualMachineRepairGuestAgentRequest{} }
func (m *VirtualMachineRepairGuestAgentRequest) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRepairGuestAgentRequest) ProtoMessage()    {}
func (*VirtualMachineRepairGuestAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{12}
}

func (m *VirtualMachineRepairGuestAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRepairGuestAgentRequest.Unmarshal(m, b)
}
func (m *VirtualMachineRepairGuestAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRepairGuestAgentRequest.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRepairGuestAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRepairGuestAgentRequest.Merge(m, src)
}
func (m *VirtualMachineRepairGuestAgentRequest) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRepairGuestAgentRequest.Size(m)
}
func (m *VirtualMachineRepairGuestAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRepairGuestAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRepairGuestAgentRequest proto.InternalMessageInfo

func (m *VirtualMachineRepairGuestAgentRequest) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

type VirtualMachineRepairGuestAgentResponse struct {
	Result               *wrappers.BoolValue `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VirtualMachineRepairGuestAgentResponse) Reset() {
	*m = VirtualMachineRepairGuestAgentResponse{}
}
func (m *VirtualMachineRepairGuestAgentResponse) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRepairGuestAgentResponse) ProtoMessage()    {}
func (*VirtualMachineRepairGuestAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2b9c6e6135d476, []int{13}
}

func (m *VirtualMachineRepairGuestAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRepairGuestAgentResponse.Unmarshal(m, b)
}
func (m *VirtualMachineRepairGuestAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRepairGuestAgentResponse.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRepairGuestAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRepairGuestAgentResponse.Merge(m, src)
}
func (m *VirtualMachineRepairGuestAgentResponse) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRepairGuestAgentResponse.Size(m)
}
func (m *VirtualMachineRepairGuestAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRepairGuestAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRepairGuestAgentResponse proto.InternalMessageInfo

func (m *VirtualMachineRepairGuestAgentResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *VirtualMachineRepairGuestAgentResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterVirtualMachineRequest)(nil), "moc.mochostagent.compute.RegisterVirtualMachineRequest")
	proto.RegisterType((*RegisterVirtualMachineInstanceView)(nil), "moc.mochostagent.compute.RegisterVirtualMachineInstanceView")
	proto.RegisterType((*RegisterVirtualMachineResponse)(nil), "moc.mochostagent.compute.RegisterVirtualMachineResponse")
	proto.RegisterType((*DeregisterVirtualMachineRequest)(nil), "moc.mochostagent.compute.DeregisterVirtualMachineRequest")
	proto.RegisterType((*DeregisterVirtualMachineInstanceView)(nil), "moc.mochostagent.compute.DeregisterVirtualMachineInstanceView")
	proto.RegisterType((*DeregisterVirtualMachineResponse)(nil), "moc.mochostagent.compute.DeregisterVirtualMachineResponse")
	proto.RegisterType((*OperatingSystemConfiguration)(nil), "moc.mochostagent.compute.OperatingSystemConfiguration")
	proto.RegisterType((*VirtualMachine)(nil), "moc.mochostagent.compute.VirtualMachine")
	proto.RegisterType((*VirtualMachineRunCommandRequest)(nil), "moc.mochostagent.compute.VirtualMachineRunCommandRequest")
	proto.RegisterType((*VirtualMachineRunCommandResponse)(nil), "moc.mochostagent.compute.VirtualMachineRunCommandResponse")
	proto.RegisterType((*GuestAgentInfoRequest)(nil), "moc.mochostagent.compute.GuestAgentInfoRequest")
	proto.RegisterType((*GuestAgentInfoResponse)(nil), "moc.mochostagent.compute.GuestAgentInfoResponse")
	proto.RegisterType((*VirtualMachineRepairGuestAgentRequest)(nil), "moc.mochostagent.compute.VirtualMachineRepairGuestAgentRequest")
	proto.RegisterType((*VirtualMachineRepairGuestAgentResponse)(nil), "moc.mochostagent.compute.VirtualMachineRepairGuestAgentResponse")
}

func init() {
	proto.RegisterFile("moc_mochostagent_virtualmachine.proto", fileDescriptor_1e2b9c6e6135d476)
}

var fileDescriptor_1e2b9c6e6135d476 = []byte{
	// 937 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xee, 0x3a, 0xa9, 0xc1, 0xaf, 0x4b, 0x94, 0x0c, 0x60, 0x5c, 0x43, 0x5a, 0x6b, 0x69, 0xa3,
	0xb4, 0x20, 0xbb, 0xb8, 0x12, 0x5f, 0x42, 0x40, 0xe2, 0xa6, 0x6d, 0x0e, 0xa1, 0xd1, 0x24, 0xe4,
	0x80, 0x90, 0xca, 0x64, 0x3d, 0x5e, 0x8f, 0xf0, 0xce, 0x2c, 0x33, 0xb3, 0x04, 0x5f, 0x38, 0x20,
	0x81, 0xb8, 0x70, 0xca, 0x81, 0x1b, 0x88, 0x1f, 0xc1, 0xff, 0x43, 0x3b, 0x3b, 0xae, 0x77, 0xd7,
	0xbb, 0x76, 0x12, 0xd4, 0x93, 0xbd, 0xf3, 0x7e, 0x3d, 0xcf, 0xfb, 0x35, 0x03, 0x77, 0x03, 0xe1,
	0x3d, 0x0f, 0x84, 0x37, 0x12, 0x4a, 0x13, 0x9f, 0x72, 0xfd, 0xfc, 0x47, 0x26, 0x75, 0x44, 0xc6,
	0x01, 0xf1, 0x46, 0x8c, 0xd3, 0x4e, 0x28, 0x85, 0x16, 0xa8, 0x19, 0x08, 0xaf, 0x93, 0x56, 0xeb,
	0x78, 0x22, 0x08, 0x23, 0x4d, 0x5b, 0x6f, 0xfb, 0x42, 0xf8, 0x63, 0xda, 0x35, 0x7a, 0xa7, 0xd1,
	0xb0, 0x4b, 0x83, 0x50, 0x4f, 0x12, 0xb3, 0xd6, 0xad, 0xbc, 0xf0, 0x4c, 0x92, 0x30, 0xa4, 0x52,
	0x59, 0xf9, 0x5b, 0x71, 0x74, 0x4f, 0x04, 0x81, 0xe0, 0xf6, 0x67, 0x6a, 0x98, 0x15, 0xc4, 0x91,
	0x32, 0xf2, 0xcd, 0x94, 0x9c, 0x0b, 0xcd, 0x86, 0xcc, 0x23, 0x9a, 0x4d, 0xc5, 0xee, 0xdf, 0x0e,
	0x6c, 0x62, 0xea, 0x33, 0xa5, 0xa9, 0x3c, 0x49, 0xf8, 0x1c, 0x24, 0x7c, 0x30, 0xfd, 0x21, 0xa2,
	0x4a, 0xa3, 0x43, 0x58, 0xcb, 0x0a, 0x9a, 0x4e, 0xdb, 0xd9, 0xae, 0xf7, 0xb6, 0x3b, 0x65, 0x4c,
	0x3b, 0x39, 0x47, 0x39, 0x7b, 0xf4, 0x3e, 0x6c, 0x9c, 0x11, 0xa6, 0x1f, 0x0b, 0xd9, 0x17, 0x9c,
	0x53, 0x2f, 0x86, 0xd3, 0xac, 0xb4, 0x9d, 0xed, 0x57, 0xf1, 0xbc, 0xc0, 0xc5, 0xe0, 0x16, 0x03,
	0xdc, 0xe7, 0x4a, 0x13, 0xee, 0xd1, 0x13, 0x46, 0xcf, 0x50, 0x03, 0xaa, 0xcf, 0x22, 0x1d, 0x46,
	0xda, 0xa0, 0xab, 0x61, 0xfb, 0x85, 0xde, 0x80, 0xeb, 0x7b, 0x52, 0x0a, 0x69, 0xfc, 0xd7, 0x70,
	0xf2, 0xe1, 0xfe, 0xe2, 0xc0, 0xad, 0x32, 0xd6, 0x2a, 0x14, 0x5c, 0x51, 0xf4, 0x1d, 0xdc, 0x48,
	0x07, 0xb0, 0xa4, 0x3f, 0x2b, 0x27, 0xbd, 0x1c, 0x24, 0xce, 0x78, 0x74, 0x0f, 0xe0, 0xf6, 0x23,
	0x2a, 0x17, 0xe6, 0xfe, 0x3e, 0xac, 0xe7, 0xdc, 0x0d, 0x2c, 0xbf, 0xb9, 0x73, 0xf7, 0x18, 0xee,
	0x94, 0xb9, 0xfb, 0x1f, 0x99, 0xfa, 0xcd, 0x81, 0x76, 0x39, 0x4a, 0x9b, 0xab, 0xd3, 0xc2, 0x5c,
	0x7d, 0x5e, 0x9e, 0xab, 0x8b, 0x00, 0xcd, 0x65, 0xeb, 0x10, 0xde, 0x79, 0x16, 0x52, 0x49, 0x34,
	0xe3, 0xfe, 0xd1, 0x44, 0x69, 0x1a, 0xf4, 0x05, 0x1f, 0x32, 0x3f, 0x92, 0xa6, 0x9d, 0xd1, 0x03,
	0xa8, 0x0a, 0xa5, 0x27, 0x61, 0xd2, 0x9e, 0x6b, 0xbd, 0xa6, 0x89, 0x9e, 0x33, 0x39, 0x9e, 0x84,
	0x14, 0x5b, 0x3d, 0xf7, 0xaf, 0x4a, 0xbe, 0xb3, 0x11, 0x82, 0x55, 0x4e, 0x02, 0x6a, 0x33, 0x63,
	0xfe, 0xa3, 0x35, 0xa8, 0xb0, 0x81, 0x4d, 0x4a, 0x85, 0x0d, 0xd0, 0x63, 0xa8, 0x08, 0xd5, 0x5c,
	0x31, 0x14, 0x3f, 0x2c, 0xa7, 0xb8, 0x08, 0x2c, 0xae, 0x08, 0x85, 0xde, 0x85, 0x2a, 0xe5, 0x9a,
	0xe9, 0x49, 0x73, 0xd5, 0xf8, 0xaa, 0x1b, 0x5f, 0x7b, 0xe6, 0x08, 0x5b, 0x11, 0xda, 0x84, 0x55,
	0x4d, 0x7c, 0xd5, 0xbc, 0x6e, 0x54, 0x6a, 0x46, 0xe5, 0x98, 0xf8, 0x0a, 0x9b, 0x63, 0xf4, 0x2d,
	0x34, 0xfc, 0xb8, 0x51, 0x76, 0xe2, 0xd0, 0x99, 0x12, 0x54, 0x8d, 0xc1, 0x1d, 0x63, 0x90, 0x25,
	0x39, 0xa7, 0x8b, 0x4b, 0x7c, 0xb8, 0xe7, 0x2b, 0x70, 0x3b, 0x57, 0xf1, 0x88, 0xf7, 0x45, 0x10,
	0x10, 0x3e, 0x78, 0x79, 0xdb, 0x61, 0x07, 0xaa, 0x47, 0x22, 0x92, 0x1e, 0x35, 0x39, 0xaf, 0xf7,
	0xee, 0x15, 0x70, 0x98, 0xe1, 0x38, 0xf2, 0x24, 0x0b, 0x75, 0x62, 0x80, 0xad, 0x21, 0x62, 0x70,
	0x73, 0xa6, 0xb1, 0xcf, 0xc3, 0x48, 0x1f, 0x12, 0x49, 0x02, 0xaa, 0xa9, 0x8c, 0x2b, 0xb7, 0xb2,
	0x5d, 0xef, 0xbd, 0xb7, 0xd0, 0x6b, 0xd6, 0x06, 0x97, 0x7b, 0x43, 0x6d, 0xa8, 0xdb, 0x4a, 0x0b,
	0xbe, 0xff, 0xc8, 0x94, 0xb2, 0x86, 0xd3, 0x47, 0xc8, 0x85, 0x1a, 0x8e, 0xf8, 0x8e, 0xfa, 0x5a,
	0x51, 0x69, 0xea, 0x58, 0xdb, 0x5d, 0xfd, 0xfd, 0xdf, 0xa6, 0x83, 0x67, 0xc7, 0xe8, 0x3e, 0xbc,
	0x66, 0x3e, 0x0e, 0x89, 0x52, 0x67, 0x42, 0x0e, 0x4c, 0xf9, 0xa6, 0x7a, 0x59, 0x91, 0x7b, 0xee,
	0x40, 0xbb, 0xbc, 0x2a, 0x76, 0x22, 0x0f, 0x0a, 0x27, 0xf2, 0xde, 0x12, 0xd2, 0x65, 0xc3, 0x97,
	0x67, 0x59, 0x99, 0x63, 0xe9, 0xf6, 0xe1, 0xcd, 0x27, 0xa9, 0x2e, 0x1a, 0x8a, 0xab, 0xac, 0xb0,
	0x9f, 0xa1, 0x91, 0x77, 0x62, 0xf9, 0x6c, 0xc1, 0x2b, 0x27, 0x54, 0xaa, 0xf8, 0xa2, 0x48, 0xa8,
	0xdc, 0x48, 0xa8, 0x24, 0x67, 0x78, 0x2a, 0x44, 0x5b, 0x70, 0xfd, 0x48, 0x13, 0x9d, 0xf4, 0xce,
	0x5a, 0x6f, 0xdd, 0x68, 0x3d, 0xa5, 0x64, 0xac, 0x47, 0xe6, 0x1c, 0x27, 0xe2, 0xd9, 0xb2, 0x5b,
	0x49, 0x2f, 0xbb, 0x09, 0xdc, 0xcd, 0x6f, 0xb8, 0x90, 0x30, 0x39, 0xc3, 0xf4, 0xd2, 0xba, 0xde,
	0x95, 0xb0, 0xb5, 0x2c, 0xb4, 0x4d, 0x45, 0x0f, 0xaa, 0x98, 0xaa, 0x68, 0xac, 0x6d, 0xcc, 0x56,
	0x27, 0x79, 0x3a, 0x74, 0xa6, 0x4f, 0x87, 0xce, 0xae, 0x10, 0xe3, 0x13, 0x32, 0x8e, 0x28, 0xb6,
	0x9a, 0xc5, 0xbb, 0xbd, 0xf7, 0x4f, 0x15, 0x5e, 0x2f, 0xd8, 0x0d, 0xe8, 0x0f, 0x07, 0x1a, 0xc5,
	0xb7, 0x19, 0xfa, 0xe8, 0xb2, 0xf7, 0x9f, 0xcd, 0x58, 0xeb, 0xe3, 0xcb, 0x1b, 0x26, 0x7c, 0xdd,
	0x6b, 0xe8, 0xdc, 0x81, 0x66, 0xd9, 0x8d, 0x81, 0x3e, 0xb9, 0xfc, 0x2d, 0x33, 0xc5, 0xf4, 0xe9,
	0x55, 0x4c, 0x5f, 0xa0, 0xfa, 0xd5, 0x01, 0x98, 0x0d, 0xcf, 0x22, 0x1c, 0x4b, 0x76, 0xe8, 0x22,
	0x1c, 0xcb, 0x06, 0xdd, 0xbd, 0x86, 0x9e, 0xc2, 0x46, 0x7f, 0x44, 0xbd, 0xef, 0xbf, 0x4a, 0x3d,
	0xee, 0x50, 0x63, 0xae, 0x29, 0xf6, 0xe2, 0xc7, 0x66, 0xeb, 0xa6, 0x09, 0x95, 0x56, 0x4d, 0x79,
	0xfa, 0x09, 0x36, 0x9e, 0x50, 0x9d, 0x9d, 0x40, 0xd4, 0x2d, 0x07, 0x57, 0x38, 0xf0, 0xad, 0x07,
	0x17, 0x37, 0x78, 0x11, 0xf9, 0x4f, 0x07, 0xd6, 0xf3, 0x0d, 0x8f, 0xbe, 0xb8, 0x70, 0x5a, 0x8a,
	0xa7, 0xb4, 0xf5, 0xe5, 0xd5, 0x1d, 0x4c, 0x91, 0xed, 0x3e, 0xfc, 0xe6, 0x03, 0x9f, 0xe9, 0x51,
	0x74, 0x1a, 0x9b, 0x76, 0x03, 0xe6, 0x49, 0xa1, 0xc4, 0x50, 0x77, 0x03, 0xe1, 0x75, 0x65, 0xe8,
	0x75, 0xd3, 0xde, 0xbb, 0xd6, 0xfb, 0x69, 0xd5, 0x64, 0xfd, 0xe1, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x3b, 0x60, 0x74, 0xda, 0x33, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VirtualMachineAgentClient is the client API for VirtualMachineAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtualMachineAgentClient interface {
	RegisterVirtualMachine(ctx context.Context, in *RegisterVirtualMachineRequest, opts ...grpc.CallOption) (*RegisterVirtualMachineResponse, error)
	DeregisterVirtualMachine(ctx context.Context, in *DeregisterVirtualMachineRequest, opts ...grpc.CallOption) (*DeregisterVirtualMachineResponse, error)
	RunCommand(ctx context.Context, in *VirtualMachineRunCommandRequest, opts ...grpc.CallOption) (*VirtualMachineRunCommandResponse, error)
	CheckNotification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.NotificationResponse, error)
	GetGuestAgentInfo(ctx context.Context, in *GuestAgentInfoRequest, opts ...grpc.CallOption) (*GuestAgentInfoResponse, error)
	RepairGuestAgent(ctx context.Context, in *VirtualMachineRepairGuestAgentRequest, opts ...grpc.CallOption) (*VirtualMachineRepairGuestAgentResponse, error)
}

type virtualMachineAgentClient struct {
	cc *grpc.ClientConn
}

func NewVirtualMachineAgentClient(cc *grpc.ClientConn) VirtualMachineAgentClient {
	return &virtualMachineAgentClient{cc}
}

func (c *virtualMachineAgentClient) RegisterVirtualMachine(ctx context.Context, in *RegisterVirtualMachineRequest, opts ...grpc.CallOption) (*RegisterVirtualMachineResponse, error) {
	out := new(RegisterVirtualMachineResponse)
	err := c.cc.Invoke(ctx, "/moc.mochostagent.compute.VirtualMachineAgent/RegisterVirtualMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) DeregisterVirtualMachine(ctx context.Context, in *DeregisterVirtualMachineRequest, opts ...grpc.CallOption) (*DeregisterVirtualMachineResponse, error) {
	out := new(DeregisterVirtualMachineResponse)
	err := c.cc.Invoke(ctx, "/moc.mochostagent.compute.VirtualMachineAgent/DeregisterVirtualMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) RunCommand(ctx context.Context, in *VirtualMachineRunCommandRequest, opts ...grpc.CallOption) (*VirtualMachineRunCommandResponse, error) {
	out := new(VirtualMachineRunCommandResponse)
	err := c.cc.Invoke(ctx, "/moc.mochostagent.compute.VirtualMachineAgent/RunCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) CheckNotification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.NotificationResponse, error) {
	out := new(common.NotificationResponse)
	err := c.cc.Invoke(ctx, "/moc.mochostagent.compute.VirtualMachineAgent/CheckNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) GetGuestAgentInfo(ctx context.Context, in *GuestAgentInfoRequest, opts ...grpc.CallOption) (*GuestAgentInfoResponse, error) {
	out := new(GuestAgentInfoResponse)
	err := c.cc.Invoke(ctx, "/moc.mochostagent.compute.VirtualMachineAgent/GetGuestAgentInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) RepairGuestAgent(ctx context.Context, in *VirtualMachineRepairGuestAgentRequest, opts ...grpc.CallOption) (*VirtualMachineRepairGuestAgentResponse, error) {
	out := new(VirtualMachineRepairGuestAgentResponse)
	err := c.cc.Invoke(ctx, "/moc.mochostagent.compute.VirtualMachineAgent/RepairGuestAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualMachineAgentServer is the server API for VirtualMachineAgent service.
type VirtualMachineAgentServer interface {
	RegisterVirtualMachine(context.Context, *RegisterVirtualMachineRequest) (*RegisterVirtualMachineResponse, error)
	DeregisterVirtualMachine(context.Context, *DeregisterVirtualMachineRequest) (*DeregisterVirtualMachineResponse, error)
	RunCommand(context.Context, *VirtualMachineRunCommandRequest) (*VirtualMachineRunCommandResponse, error)
	CheckNotification(context.Context, *empty.Empty) (*common.NotificationResponse, error)
	GetGuestAgentInfo(context.Context, *GuestAgentInfoRequest) (*GuestAgentInfoResponse, error)
	RepairGuestAgent(context.Context, *VirtualMachineRepairGuestAgentRequest) (*VirtualMachineRepairGuestAgentResponse, error)
}

// UnimplementedVirtualMachineAgentServer can be embedded to have forward compatible implementations.
type UnimplementedVirtualMachineAgentServer struct {
}

func (*UnimplementedVirtualMachineAgentServer) RegisterVirtualMachine(ctx context.Context, req *RegisterVirtualMachineRequest) (*RegisterVirtualMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVirtualMachine not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) DeregisterVirtualMachine(ctx context.Context, req *DeregisterVirtualMachineRequest) (*DeregisterVirtualMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterVirtualMachine not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) RunCommand(ctx context.Context, req *VirtualMachineRunCommandRequest) (*VirtualMachineRunCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCommand not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) CheckNotification(ctx context.Context, req *empty.Empty) (*common.NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNotification not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) GetGuestAgentInfo(ctx context.Context, req *GuestAgentInfoRequest) (*GuestAgentInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGuestAgentInfo not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) RepairGuestAgent(ctx context.Context, req *VirtualMachineRepairGuestAgentRequest) (*VirtualMachineRepairGuestAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepairGuestAgent not implemented")
}

func RegisterVirtualMachineAgentServer(s *grpc.Server, srv VirtualMachineAgentServer) {
	s.RegisterService(&_VirtualMachineAgent_serviceDesc, srv)
}

func _VirtualMachineAgent_RegisterVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).RegisterVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.mochostagent.compute.VirtualMachineAgent/RegisterVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).RegisterVirtualMachine(ctx, req.(*RegisterVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_DeregisterVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).DeregisterVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.mochostagent.compute.VirtualMachineAgent/DeregisterVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).DeregisterVirtualMachine(ctx, req.(*DeregisterVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachineRunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.mochostagent.compute.VirtualMachineAgent/RunCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).RunCommand(ctx, req.(*VirtualMachineRunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_CheckNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).CheckNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.mochostagent.compute.VirtualMachineAgent/CheckNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).CheckNotification(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_GetGuestAgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestAgentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).GetGuestAgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.mochostagent.compute.VirtualMachineAgent/GetGuestAgentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).GetGuestAgentInfo(ctx, req.(*GuestAgentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_RepairGuestAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachineRepairGuestAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).RepairGuestAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.mochostagent.compute.VirtualMachineAgent/RepairGuestAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).RepairGuestAgent(ctx, req.(*VirtualMachineRepairGuestAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VirtualMachineAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.mochostagent.compute.VirtualMachineAgent",
	HandlerType: (*VirtualMachineAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterVirtualMachine",
			Handler:    _VirtualMachineAgent_RegisterVirtualMachine_Handler,
		},
		{
			MethodName: "DeregisterVirtualMachine",
			Handler:    _VirtualMachineAgent_DeregisterVirtualMachine_Handler,
		},
		{
			MethodName: "RunCommand",
			Handler:    _VirtualMachineAgent_RunCommand_Handler,
		},
		{
			MethodName: "CheckNotification",
			Handler:    _VirtualMachineAgent_CheckNotification_Handler,
		},
		{
			MethodName: "GetGuestAgentInfo",
			Handler:    _VirtualMachineAgent_GetGuestAgentInfo_Handler,
		},
		{
			MethodName: "RepairGuestAgent",
			Handler:    _VirtualMachineAgent_RepairGuestAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_mochostagent_virtualmachine.proto",
}
