// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_hostagent_keyvault.proto

package security

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyVaultRequest struct {
	KeyVaults            []*KeyVault      `protobuf:"bytes,1,rep,name=KeyVaults,proto3" json:"KeyVaults,omitempty"`
	OperationType        common.Operation `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *KeyVaultRequest) Reset()         { *m = KeyVaultRequest{} }
func (m *KeyVaultRequest) String() string { return proto.CompactTextString(m) }
func (*KeyVaultRequest) ProtoMessage()    {}
func (*KeyVaultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cc873d8ed5af0e, []int{0}
}

func (m *KeyVaultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyVaultRequest.Unmarshal(m, b)
}
func (m *KeyVaultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyVaultRequest.Marshal(b, m, deterministic)
}
func (m *KeyVaultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyVaultRequest.Merge(m, src)
}
func (m *KeyVaultRequest) XXX_Size() int {
	return xxx_messageInfo_KeyVaultRequest.Size(m)
}
func (m *KeyVaultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyVaultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyVaultRequest proto.InternalMessageInfo

func (m *KeyVaultRequest) GetKeyVaults() []*KeyVault {
	if m != nil {
		return m.KeyVaults
	}
	return nil
}

func (m *KeyVaultRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type KeyVaultResponse struct {
	KeyVaults            []*KeyVault         `protobuf:"bytes,1,rep,name=KeyVaults,proto3" json:"KeyVaults,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *KeyVaultResponse) Reset()         { *m = KeyVaultResponse{} }
func (m *KeyVaultResponse) String() string { return proto.CompactTextString(m) }
func (*KeyVaultResponse) ProtoMessage()    {}
func (*KeyVaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cc873d8ed5af0e, []int{1}
}

func (m *KeyVaultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyVaultResponse.Unmarshal(m, b)
}
func (m *KeyVaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyVaultResponse.Marshal(b, m, deterministic)
}
func (m *KeyVaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyVaultResponse.Merge(m, src)
}
func (m *KeyVaultResponse) XXX_Size() int {
	return xxx_messageInfo_KeyVaultResponse.Size(m)
}
func (m *KeyVaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyVaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyVaultResponse proto.InternalMessageInfo

func (m *KeyVaultResponse) GetKeyVaults() []*KeyVault {
	if m != nil {
		return m.KeyVaults
	}
	return nil
}

func (m *KeyVaultResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *KeyVaultResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type KeyVault struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Secrets              []*Secret      `protobuf:"bytes,3,rep,name=Secrets,proto3" json:"Secrets,omitempty"`
	GroupName            string         `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Status               *common.Status `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Entity               *common.Entity `protobuf:"bytes,6,opt,name=entity,proto3" json:"entity,omitempty"`
	Tags                 *common.Tags   `protobuf:"bytes,7,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *KeyVault) Reset()         { *m = KeyVault{} }
func (m *KeyVault) String() string { return proto.CompactTextString(m) }
func (*KeyVault) ProtoMessage()    {}
func (*KeyVault) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cc873d8ed5af0e, []int{2}
}

func (m *KeyVault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyVault.Unmarshal(m, b)
}
func (m *KeyVault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyVault.Marshal(b, m, deterministic)
}
func (m *KeyVault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyVault.Merge(m, src)
}
func (m *KeyVault) XXX_Size() int {
	return xxx_messageInfo_KeyVault.Size(m)
}
func (m *KeyVault) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyVault.DiscardUnknown(m)
}

var xxx_messageInfo_KeyVault proto.InternalMessageInfo

func (m *KeyVault) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KeyVault) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *KeyVault) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *KeyVault) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *KeyVault) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KeyVault) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *KeyVault) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyVaultRequest)(nil), "moc.hostagent.security.KeyVaultRequest")
	proto.RegisterType((*KeyVaultResponse)(nil), "moc.hostagent.security.KeyVaultResponse")
	proto.RegisterType((*KeyVault)(nil), "moc.hostagent.security.KeyVault")
}

func init() { proto.RegisterFile("moc_hostagent_keyvault.proto", fileDescriptor_82cc873d8ed5af0e) }

var fileDescriptor_82cc873d8ed5af0e = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xdf, 0x6a, 0xd4, 0x40,
	0x14, 0xc6, 0xcd, 0xee, 0x36, 0x35, 0xb3, 0x74, 0x95, 0x41, 0x34, 0x84, 0x5a, 0x96, 0xf5, 0xc2,
	0xbd, 0x9a, 0x60, 0xf4, 0xc2, 0x2b, 0xc1, 0x42, 0x2f, 0x44, 0x50, 0x98, 0x96, 0x5e, 0x08, 0x52,
	0x66, 0xa7, 0xa7, 0x69, 0x68, 0x92, 0x13, 0xe7, 0x4f, 0x25, 0x4f, 0xe0, 0x4b, 0xf8, 0x8e, 0xbe,
	0x82, 0xe4, 0x24, 0xd9, 0xb5, 0xa0, 0xf4, 0xc2, 0xab, 0x24, 0xe7, 0xfc, 0xe6, 0xfb, 0xbe, 0x39,
	0x27, 0xec, 0xb0, 0x42, 0x7d, 0x71, 0x8d, 0xd6, 0xa9, 0x1c, 0x6a, 0x77, 0x71, 0x03, 0xed, 0xad,
	0xf2, 0xa5, 0x13, 0x8d, 0x41, 0x87, 0xfc, 0x69, 0x85, 0x5a, 0x6c, 0xbb, 0xc2, 0x82, 0xf6, 0xa6,
	0x70, 0x6d, 0x72, 0x94, 0x23, 0xe6, 0x25, 0xa4, 0x44, 0x6d, 0xfc, 0x55, 0xfa, 0xdd, 0xa8, 0xa6,
	0x01, 0x63, 0xfb, 0x73, 0xc9, 0xb3, 0x4e, 0x55, 0x63, 0x55, 0x61, 0x3d, 0x3c, 0x86, 0x46, 0x72,
	0xd7, 0xce, 0x82, 0x36, 0x30, 0x98, 0xad, 0x7e, 0x04, 0xec, 0xd1, 0x47, 0x68, 0xcf, 0x3b, 0x7f,
	0x09, 0xdf, 0x3c, 0x58, 0xc7, 0xdf, 0xb1, 0x68, 0x2c, 0xd9, 0x38, 0x58, 0x4e, 0xd7, 0xf3, 0x6c,
	0x29, 0xfe, 0x1e, 0x4a, 0x6c, 0xcf, 0xee, 0x8e, 0xf0, 0x37, 0xec, 0xe0, 0x73, 0x03, 0x46, 0xb9,
	0x02, 0xeb, 0xb3, 0xb6, 0x81, 0x78, 0xb2, 0x0c, 0xd6, 0x8b, 0x6c, 0x41, 0x1a, 0xdb, 0x8e, 0xbc,
	0x0b, 0xad, 0x7e, 0x06, 0xec, 0xf1, 0x2e, 0x89, 0x6d, 0xb0, 0xb6, 0xf0, 0xdf, 0x51, 0x32, 0x16,
	0x4a, 0xb0, 0xbe, 0x74, 0x94, 0x61, 0x9e, 0x25, 0xa2, 0x1f, 0xa2, 0x18, 0x87, 0x28, 0x8e, 0x11,
	0xcb, 0x73, 0x55, 0x7a, 0x90, 0x03, 0xc9, 0x9f, 0xb0, 0xbd, 0x13, 0x63, 0xd0, 0xc4, 0xd3, 0x65,
	0xb0, 0x8e, 0x64, 0xff, 0xb1, 0xfa, 0x15, 0xb0, 0x87, 0xa3, 0x2e, 0xe7, 0x6c, 0x56, 0xab, 0x0a,
	0xe2, 0x80, 0x08, 0x7a, 0xe7, 0x0b, 0x36, 0x29, 0x2e, 0xc9, 0x26, 0x92, 0x93, 0xe2, 0x92, 0xbf,
	0x65, 0xfb, 0xa7, 0x34, 0x69, 0x1b, 0x4f, 0x29, 0xf8, 0xd1, 0xbf, 0x82, 0xf7, 0x98, 0x1c, 0x71,
	0x7e, 0xc8, 0xa2, 0xdc, 0xa0, 0x6f, 0x3e, 0x75, 0x16, 0x33, 0x12, 0xdc, 0x15, 0xf8, 0x0b, 0x16,
	0x5a, 0xa7, 0x9c, 0xb7, 0xf1, 0x1e, 0x5d, 0x69, 0x4e, 0xb2, 0xa7, 0x54, 0x92, 0x43, 0xab, 0x83,
	0xa0, 0x76, 0x85, 0x6b, 0xe3, 0xf0, 0x0f, 0xe8, 0x84, 0x4a, 0x72, 0x68, 0xf1, 0xe7, 0x6c, 0xe6,
	0x54, 0x6e, 0xe3, 0x7d, 0x42, 0x22, 0x42, 0xce, 0x54, 0x6e, 0x25, 0x95, 0xb3, 0x9a, 0x1d, 0x8c,
	0x17, 0x7e, 0xdf, 0x05, 0xe6, 0x5f, 0x59, 0xf8, 0xa1, 0xbe, 0xc5, 0x1b, 0xe0, 0x2f, 0xef, 0xdd,
	0x41, 0xff, 0x2b, 0x25, 0xeb, 0xfb, 0xc1, 0x7e, 0xd3, 0xab, 0x07, 0xc7, 0xaf, 0xbe, 0xa4, 0x79,
	0xe1, 0xae, 0xfd, 0x46, 0x68, 0xac, 0xd2, 0xaa, 0xd0, 0x06, 0x2d, 0x5e, 0xb9, 0xb4, 0x42, 0x9d,
	0x9a, 0x46, 0xa7, 0x5b, 0x95, 0x74, 0x54, 0xd9, 0x84, 0xb4, 0xc6, 0xd7, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xe2, 0xc8, 0x6f, 0x21, 0x51, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KeyVaultAgentClient is the client API for KeyVaultAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyVaultAgentClient interface {
	Invoke(ctx context.Context, in *KeyVaultRequest, opts ...grpc.CallOption) (*KeyVaultResponse, error)
}

type keyVaultAgentClient struct {
	cc *grpc.ClientConn
}

func NewKeyVaultAgentClient(cc *grpc.ClientConn) KeyVaultAgentClient {
	return &keyVaultAgentClient{cc}
}

func (c *keyVaultAgentClient) Invoke(ctx context.Context, in *KeyVaultRequest, opts ...grpc.CallOption) (*KeyVaultResponse, error) {
	out := new(KeyVaultResponse)
	err := c.cc.Invoke(ctx, "/moc.hostagent.security.KeyVaultAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyVaultAgentServer is the server API for KeyVaultAgent service.
type KeyVaultAgentServer interface {
	Invoke(context.Context, *KeyVaultRequest) (*KeyVaultResponse, error)
}

// UnimplementedKeyVaultAgentServer can be embedded to have forward compatible implementations.
type UnimplementedKeyVaultAgentServer struct {
}

func (*UnimplementedKeyVaultAgentServer) Invoke(ctx context.Context, req *KeyVaultRequest) (*KeyVaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterKeyVaultAgentServer(s *grpc.Server, srv KeyVaultAgentServer) {
	s.RegisterService(&_KeyVaultAgent_serviceDesc, srv)
}

func _KeyVaultAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyVaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyVaultAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.hostagent.security.KeyVaultAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyVaultAgentServer).Invoke(ctx, req.(*KeyVaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyVaultAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.hostagent.security.KeyVaultAgent",
	HandlerType: (*KeyVaultAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _KeyVaultAgent_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_hostagent_keyvault.proto",
}
