// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_hostagent_identity.proto

package security

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IdentityRequest struct {
	Identitys            []*Identity      `protobuf:"bytes,1,rep,name=Identitys,proto3" json:"Identitys,omitempty"`
	OperationType        common.Operation `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IdentityRequest) Reset()         { *m = IdentityRequest{} }
func (m *IdentityRequest) String() string { return proto.CompactTextString(m) }
func (*IdentityRequest) ProtoMessage()    {}
func (*IdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16e45ab17ec07ca, []int{0}
}

func (m *IdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityRequest.Unmarshal(m, b)
}
func (m *IdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityRequest.Marshal(b, m, deterministic)
}
func (m *IdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityRequest.Merge(m, src)
}
func (m *IdentityRequest) XXX_Size() int {
	return xxx_messageInfo_IdentityRequest.Size(m)
}
func (m *IdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityRequest proto.InternalMessageInfo

func (m *IdentityRequest) GetIdentitys() []*Identity {
	if m != nil {
		return m.Identitys
	}
	return nil
}

func (m *IdentityRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type IdentityResponse struct {
	Identitys            []*Identity         `protobuf:"bytes,1,rep,name=Identitys,proto3" json:"Identitys,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *IdentityResponse) Reset()         { *m = IdentityResponse{} }
func (m *IdentityResponse) String() string { return proto.CompactTextString(m) }
func (*IdentityResponse) ProtoMessage()    {}
func (*IdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16e45ab17ec07ca, []int{1}
}

func (m *IdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityResponse.Unmarshal(m, b)
}
func (m *IdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityResponse.Marshal(b, m, deterministic)
}
func (m *IdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityResponse.Merge(m, src)
}
func (m *IdentityResponse) XXX_Size() int {
	return xxx_messageInfo_IdentityResponse.Size(m)
}
func (m *IdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityResponse proto.InternalMessageInfo

func (m *IdentityResponse) GetIdentitys() []*Identity {
	if m != nil {
		return m.Identitys
	}
	return nil
}

func (m *IdentityResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *IdentityResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Identity struct {
	Name                 string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string                    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ResourceGroup        string                    `protobuf:"bytes,3,opt,name=resourceGroup,proto3" json:"resourceGroup,omitempty"`
	Password             string                    `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Token                string                    `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Certificate          string                    `protobuf:"bytes,6,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Status               *common.Status            `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Entity               *common.Entity            `protobuf:"bytes,8,opt,name=entity,proto3" json:"entity,omitempty"`
	Tags                 *common.Tags              `protobuf:"bytes,9,opt,name=tags,proto3" json:"tags,omitempty"`
	TokenExpiry          int64                     `protobuf:"varint,13,opt,name=tokenExpiry,proto3" json:"tokenExpiry,omitempty"`
	ClientType           common.ClientType         `protobuf:"varint,14,opt,name=clientType,proto3,enum=moc.ClientType" json:"clientType,omitempty"`
	HostFqdn             string                    `protobuf:"bytes,15,opt,name=hostFqdn,proto3" json:"hostFqdn,omitempty"`
	HostPort             int32                     `protobuf:"varint,16,opt,name=hostPort,proto3" json:"hostPort,omitempty"`
	HostAuthPort         int32                     `protobuf:"varint,17,opt,name=hostAuthPort,proto3" json:"hostAuthPort,omitempty"`
	AuthType             common.AuthenticationType `protobuf:"varint,18,opt,name=authType,proto3,enum=moc.AuthenticationType" json:"authType,omitempty"`
	Revoked              bool                      `protobuf:"varint,19,opt,name=revoked,proto3" json:"revoked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_e16e45ab17ec07ca, []int{2}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Identity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Identity) GetResourceGroup() string {
	if m != nil {
		return m.ResourceGroup
	}
	return ""
}

func (m *Identity) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Identity) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Identity) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *Identity) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Identity) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *Identity) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Identity) GetTokenExpiry() int64 {
	if m != nil {
		return m.TokenExpiry
	}
	return 0
}

func (m *Identity) GetClientType() common.ClientType {
	if m != nil {
		return m.ClientType
	}
	return common.ClientType_CONTROLPLANE
}

func (m *Identity) GetHostFqdn() string {
	if m != nil {
		return m.HostFqdn
	}
	return ""
}

func (m *Identity) GetHostPort() int32 {
	if m != nil {
		return m.HostPort
	}
	return 0
}

func (m *Identity) GetHostAuthPort() int32 {
	if m != nil {
		return m.HostAuthPort
	}
	return 0
}

func (m *Identity) GetAuthType() common.AuthenticationType {
	if m != nil {
		return m.AuthType
	}
	return common.AuthenticationType_SELFSIGNED
}

func (m *Identity) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func init() {
	proto.RegisterType((*IdentityRequest)(nil), "moc.hostagent.security.IdentityRequest")
	proto.RegisterType((*IdentityResponse)(nil), "moc.hostagent.security.IdentityResponse")
	proto.RegisterType((*Identity)(nil), "moc.hostagent.security.Identity")
}

func init() { proto.RegisterFile("moc_hostagent_identity.proto", fileDescriptor_e16e45ab17ec07ca) }

var fileDescriptor_e16e45ab17ec07ca = []byte{
	// 575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0xc7, 0x7f, 0xd9, 0xda, 0x2e, 0x3d, 0xfd, 0xb5, 0x1b, 0x06, 0x31, 0x2b, 0x02, 0x14, 0x15,
	0x04, 0xb9, 0x4a, 0x44, 0xc7, 0x35, 0xd2, 0x86, 0x06, 0xda, 0x15, 0xc8, 0x4c, 0x5c, 0x20, 0xa1,
	0x29, 0x73, 0xdc, 0xd4, 0x5a, 0x93, 0x93, 0xd9, 0x0e, 0xa3, 0x4f, 0x00, 0x0f, 0xc1, 0x0d, 0x0f,
	0xc1, 0xfb, 0xa1, 0x38, 0x7f, 0x96, 0x4a, 0x48, 0xbb, 0xe0, 0x2a, 0x3e, 0xdf, 0xef, 0xc7, 0xc7,
	0xc7, 0x27, 0xc7, 0xf0, 0x28, 0x43, 0x7e, 0xb1, 0x42, 0x6d, 0xe2, 0x54, 0xe4, 0xe6, 0x42, 0x26,
	0x22, 0x37, 0xd2, 0x6c, 0xc2, 0x42, 0xa1, 0x41, 0xf2, 0x30, 0x43, 0x1e, 0x76, 0x6e, 0xa8, 0x05,
	0x2f, 0x95, 0x34, 0x1b, 0xef, 0x49, 0x8a, 0x98, 0xae, 0x45, 0x64, 0xa9, 0xcb, 0x72, 0x19, 0xdd,
	0xa8, 0xb8, 0x28, 0x84, 0xd2, 0xf5, 0x3e, 0xef, 0xb0, 0xca, 0xca, 0x31, 0xcb, 0x30, 0x6f, 0x3e,
	0xb5, 0x31, 0xff, 0xee, 0xc0, 0xfe, 0x59, 0x73, 0x06, 0x13, 0xd7, 0xa5, 0xd0, 0x86, 0xbc, 0x86,
	0x71, 0x2b, 0x69, 0xea, 0xf8, 0xbb, 0xc1, 0x64, 0xe1, 0x87, 0x7f, 0x3f, 0x38, 0xec, 0xf6, 0xde,
	0x6e, 0x21, 0xaf, 0x60, 0xfa, 0xbe, 0x10, 0x2a, 0x36, 0x12, 0xf3, 0xf3, 0x4d, 0x21, 0xe8, 0x8e,
	0xef, 0x04, 0xb3, 0xc5, 0xcc, 0xe6, 0xe8, 0x1c, 0xb6, 0x0d, 0xcd, 0x7f, 0x3a, 0x70, 0x70, 0x5b,
	0x89, 0x2e, 0x30, 0xd7, 0xe2, 0x9f, 0x4b, 0x59, 0xc0, 0x88, 0x09, 0x5d, 0xae, 0x8d, 0xad, 0x61,
	0xb2, 0xf0, 0xc2, 0xba, 0x51, 0x61, 0xdb, 0xa8, 0xf0, 0x04, 0x71, 0xfd, 0x29, 0x5e, 0x97, 0x82,
	0x35, 0x24, 0x79, 0x00, 0xc3, 0x53, 0xa5, 0x50, 0xd1, 0x5d, 0xdf, 0x09, 0xc6, 0xac, 0x0e, 0xe6,
	0xbf, 0x06, 0xe0, 0xb6, 0x79, 0x09, 0x81, 0x41, 0x1e, 0x67, 0x82, 0x3a, 0x96, 0xb0, 0x6b, 0x32,
	0x83, 0x1d, 0x99, 0xd8, 0x63, 0xc6, 0x6c, 0x47, 0x26, 0xe4, 0x19, 0x4c, 0x95, 0xd0, 0x58, 0x2a,
	0x2e, 0xde, 0x29, 0x2c, 0x8b, 0x26, 0xdd, 0xb6, 0x48, 0x7c, 0x70, 0x8b, 0x58, 0xeb, 0x1b, 0x54,
	0x09, 0x1d, 0x54, 0xc0, 0xc9, 0xe0, 0xc7, 0x6f, 0xea, 0xb0, 0x4e, 0x25, 0x1e, 0x0c, 0x0d, 0x5e,
	0x89, 0x9c, 0x0e, 0x7b, 0x76, 0x2d, 0x91, 0xe7, 0x30, 0xe1, 0x42, 0x19, 0xb9, 0x94, 0x3c, 0x36,
	0x82, 0x8e, 0x7a, 0x44, 0xdf, 0x20, 0x4f, 0x61, 0xa4, 0x4d, 0x6c, 0x4a, 0x4d, 0xf7, 0x6c, 0x1b,
	0x26, 0xb6, 0x87, 0x1f, 0xad, 0xc4, 0x1a, 0xab, 0x82, 0xea, 0xeb, 0x51, 0xb7, 0x07, 0x9d, 0xd6,
	0x3d, 0x6d, 0x2c, 0xf2, 0x18, 0x06, 0x26, 0x4e, 0x35, 0x1d, 0x5b, 0x64, 0x6c, 0x91, 0xf3, 0x38,
	0xd5, 0xcc, 0xca, 0xc4, 0x87, 0x89, 0xad, 0xec, 0xf4, 0x5b, 0x21, 0xd5, 0x86, 0x4e, 0x7d, 0x27,
	0xd8, 0x65, 0x7d, 0x89, 0x44, 0x00, 0x7c, 0x2d, 0x45, 0x6e, 0xec, 0x64, 0xcc, 0xec, 0x64, 0xec,
	0xdb, 0x34, 0x6f, 0x3a, 0x99, 0xf5, 0x10, 0xe2, 0x81, 0x5b, 0xfd, 0xec, 0xb7, 0xd7, 0x49, 0x4e,
	0xf7, 0x6d, 0x0b, 0xbb, 0xb8, 0xf5, 0x3e, 0xa0, 0x32, 0xf4, 0xc0, 0x77, 0x82, 0x21, 0xeb, 0x62,
	0x32, 0x87, 0xff, 0xab, 0xf5, 0x71, 0x69, 0x56, 0xd6, 0xbf, 0x67, 0xfd, 0x2d, 0x8d, 0x1c, 0x81,
	0x1b, 0x97, 0x66, 0x65, 0x4b, 0x21, 0xb6, 0x94, 0x43, 0x5b, 0x4a, 0x05, 0x54, 0x17, 0xe6, 0xdd,
	0x78, 0xb2, 0x0e, 0x24, 0x14, 0xf6, 0x94, 0xf8, 0x8a, 0x57, 0x22, 0xa1, 0xf7, 0x7d, 0x27, 0x70,
	0x59, 0x1b, 0x2e, 0x72, 0x98, 0xb6, 0x23, 0x72, 0x5c, 0xcd, 0x26, 0xf9, 0x02, 0xa3, 0xb3, 0xbc,
	0xf2, 0xc8, 0x8b, 0x3b, 0xa7, 0xb6, 0x7e, 0x7c, 0x5e, 0x70, 0x37, 0x58, 0xbf, 0x8d, 0xf9, 0x7f,
	0x27, 0x2f, 0x3f, 0x47, 0xa9, 0x34, 0xab, 0xf2, 0x32, 0xe4, 0x98, 0x45, 0x99, 0xe4, 0x0a, 0x35,
	0x2e, 0x4d, 0x94, 0x21, 0x8f, 0x54, 0xc1, 0xa3, 0x2e, 0x4b, 0xd4, 0x66, 0xb9, 0x1c, 0xd9, 0xc1,
	0x3f, 0xfa, 0x13, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x38, 0xa7, 0x95, 0x67, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdentityAgentClient is the client API for IdentityAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityAgentClient interface {
	Invoke(ctx context.Context, in *IdentityRequest, opts ...grpc.CallOption) (*IdentityResponse, error)
}

type identityAgentClient struct {
	cc *grpc.ClientConn
}

func NewIdentityAgentClient(cc *grpc.ClientConn) IdentityAgentClient {
	return &identityAgentClient{cc}
}

func (c *identityAgentClient) Invoke(ctx context.Context, in *IdentityRequest, opts ...grpc.CallOption) (*IdentityResponse, error) {
	out := new(IdentityResponse)
	err := c.cc.Invoke(ctx, "/moc.hostagent.security.IdentityAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityAgentServer is the server API for IdentityAgent service.
type IdentityAgentServer interface {
	Invoke(context.Context, *IdentityRequest) (*IdentityResponse, error)
}

// UnimplementedIdentityAgentServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityAgentServer struct {
}

func (*UnimplementedIdentityAgentServer) Invoke(ctx context.Context, req *IdentityRequest) (*IdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterIdentityAgentServer(s *grpc.Server, srv IdentityAgentServer) {
	s.RegisterService(&_IdentityAgent_serviceDesc, srv)
}

func _IdentityAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.hostagent.security.IdentityAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityAgentServer).Invoke(ctx, req.(*IdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.hostagent.security.IdentityAgent",
	HandlerType: (*IdentityAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _IdentityAgent_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_hostagent_identity.proto",
}
