// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_hostagent_secret.proto

package security

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SecretRequest struct {
	Secrets              []*Secret        `protobuf:"bytes,1,rep,name=Secrets,proto3" json:"Secrets,omitempty"`
	OperationType        common.Operation `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SecretRequest) Reset()         { *m = SecretRequest{} }
func (m *SecretRequest) String() string { return proto.CompactTextString(m) }
func (*SecretRequest) ProtoMessage()    {}
func (*SecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc6049eee8d85d87, []int{0}
}

func (m *SecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretRequest.Unmarshal(m, b)
}
func (m *SecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretRequest.Marshal(b, m, deterministic)
}
func (m *SecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretRequest.Merge(m, src)
}
func (m *SecretRequest) XXX_Size() int {
	return xxx_messageInfo_SecretRequest.Size(m)
}
func (m *SecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecretRequest proto.InternalMessageInfo

func (m *SecretRequest) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *SecretRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type SecretResponse struct {
	Secrets              []*Secret           `protobuf:"bytes,1,rep,name=Secrets,proto3" json:"Secrets,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SecretResponse) Reset()         { *m = SecretResponse{} }
func (m *SecretResponse) String() string { return proto.CompactTextString(m) }
func (*SecretResponse) ProtoMessage()    {}
func (*SecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc6049eee8d85d87, []int{1}
}

func (m *SecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretResponse.Unmarshal(m, b)
}
func (m *SecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretResponse.Marshal(b, m, deterministic)
}
func (m *SecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretResponse.Merge(m, src)
}
func (m *SecretResponse) XXX_Size() int {
	return xxx_messageInfo_SecretResponse.Size(m)
}
func (m *SecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SecretResponse proto.InternalMessageInfo

func (m *SecretResponse) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *SecretResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *SecretResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Secret struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Filename             string         `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Value                string         `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	VaultId              string         `protobuf:"bytes,5,opt,name=vaultId,proto3" json:"vaultId,omitempty"`
	VaultName            string         `protobuf:"bytes,6,opt,name=vaultName,proto3" json:"vaultName,omitempty"`
	GroupName            string         `protobuf:"bytes,7,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Status               *common.Status `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Entity               *common.Entity `protobuf:"bytes,9,opt,name=entity,proto3" json:"entity,omitempty"`
	Tags                 *common.Tags   `protobuf:"bytes,10,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Secret) Reset()         { *m = Secret{} }
func (m *Secret) String() string { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()    {}
func (*Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc6049eee8d85d87, []int{2}
}

func (m *Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secret.Unmarshal(m, b)
}
func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secret.Marshal(b, m, deterministic)
}
func (m *Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secret.Merge(m, src)
}
func (m *Secret) XXX_Size() int {
	return xxx_messageInfo_Secret.Size(m)
}
func (m *Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Secret proto.InternalMessageInfo

func (m *Secret) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Secret) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Secret) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Secret) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Secret) GetVaultId() string {
	if m != nil {
		return m.VaultId
	}
	return ""
}

func (m *Secret) GetVaultName() string {
	if m != nil {
		return m.VaultName
	}
	return ""
}

func (m *Secret) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Secret) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Secret) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *Secret) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*SecretRequest)(nil), "moc.hostagent.security.SecretRequest")
	proto.RegisterType((*SecretResponse)(nil), "moc.hostagent.security.SecretResponse")
	proto.RegisterType((*Secret)(nil), "moc.hostagent.security.Secret")
}

func init() { proto.RegisterFile("moc_hostagent_secret.proto", fileDescriptor_fc6049eee8d85d87) }

var fileDescriptor_fc6049eee8d85d87 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xbf, 0x8e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0x2e, 0x71, 0xce, 0x13, 0x5d, 0x8a, 0x15, 0x82, 0x95, 0x05, 0xa7, 0x28, 0x08,
	0x94, 0xca, 0x16, 0x86, 0x82, 0x96, 0x48, 0x57, 0x5c, 0x03, 0xd2, 0xde, 0x09, 0x09, 0x9a, 0x93,
	0xe3, 0x6c, 0x1c, 0x0b, 0xdb, 0x63, 0xf6, 0x4f, 0x50, 0x2a, 0x5a, 0x1e, 0x80, 0x37, 0xe0, 0x19,
	0x78, 0x3f, 0xe4, 0x59, 0xdb, 0x80, 0x84, 0x94, 0xe2, 0x2a, 0x7b, 0xbf, 0xdf, 0x37, 0xdf, 0xac,
	0x66, 0x16, 0xc2, 0x0a, 0xb3, 0xbb, 0x3d, 0x6a, 0x93, 0xe6, 0xb2, 0x36, 0x77, 0x5a, 0x66, 0x4a,
	0x9a, 0xa8, 0x51, 0x68, 0x90, 0x3d, 0xaa, 0x30, 0x8b, 0x06, 0x16, 0x69, 0x99, 0x59, 0x55, 0x98,
	0x63, 0x78, 0x99, 0x23, 0xe6, 0xa5, 0x8c, 0xc9, 0xb5, 0xb1, 0xbb, 0xf8, 0xab, 0x4a, 0x9b, 0x46,
	0x2a, 0xed, 0xea, 0xc2, 0xc7, 0x6d, 0x66, 0x86, 0x55, 0x85, 0x75, 0xf7, 0x71, 0x60, 0xf9, 0x0d,
	0x2e, 0x6e, 0xa8, 0x81, 0x90, 0x5f, 0xac, 0xd4, 0x86, 0xbd, 0x81, 0xa9, 0x13, 0x34, 0xf7, 0x16,
	0x67, 0xab, 0x59, 0x72, 0x19, 0xfd, 0xbf, 0x67, 0xd4, 0xd5, 0xf5, 0x76, 0xf6, 0x1a, 0x2e, 0xde,
	0x37, 0x52, 0xa5, 0xa6, 0xc0, 0xfa, 0xf6, 0xd8, 0x48, 0x3e, 0x5a, 0x78, 0xab, 0x79, 0x32, 0xa7,
	0xfa, 0x81, 0x88, 0x7f, 0x4d, 0xcb, 0x1f, 0x1e, 0xcc, 0xfb, 0x1b, 0xe8, 0x06, 0x6b, 0x2d, 0xef,
	0x71, 0x85, 0x04, 0x7c, 0x21, 0xb5, 0x2d, 0x0d, 0xf5, 0x9e, 0x25, 0x61, 0xe4, 0xe6, 0x12, 0xf5,
	0x73, 0x89, 0xd6, 0x88, 0xe5, 0x87, 0xb4, 0xb4, 0x52, 0x74, 0x4e, 0xf6, 0x10, 0x26, 0x57, 0x4a,
	0xa1, 0xe2, 0x67, 0x0b, 0x6f, 0x15, 0x08, 0x77, 0x58, 0xfe, 0x1c, 0x81, 0xef, 0x52, 0x19, 0x83,
	0x71, 0x9d, 0x56, 0x92, 0x7b, 0xc4, 0xe9, 0x9f, 0xcd, 0x61, 0x54, 0x6c, 0xa9, 0x49, 0x20, 0x46,
	0xc5, 0x96, 0x85, 0x70, 0xbe, 0x2b, 0x4a, 0x49, 0x3e, 0x97, 0x33, 0x9c, 0x59, 0x08, 0x93, 0x43,
	0xdb, 0x91, 0x8f, 0x5b, 0xb0, 0x1e, 0x7f, 0xff, 0xc5, 0x3d, 0xe1, 0x24, 0xc6, 0x61, 0x7a, 0x48,
	0x6d, 0x69, 0xae, 0xb7, 0x7c, 0x42, 0x65, 0xfd, 0x91, 0x3d, 0x81, 0x80, 0x7e, 0xdf, 0xb5, 0x91,
	0x3e, 0xb1, 0x3f, 0x42, 0x4b, 0x73, 0x85, 0xb6, 0x21, 0x3a, 0x75, 0x74, 0x10, 0xd8, 0x33, 0xf0,
	0xb5, 0x49, 0x8d, 0xd5, 0xfc, 0x9c, 0xc6, 0x30, 0xa3, 0xf9, 0xdd, 0x90, 0x24, 0x3a, 0xd4, 0x9a,
	0x64, 0x6d, 0x0a, 0x73, 0xe4, 0xc1, 0x5f, 0xa6, 0x2b, 0x92, 0x44, 0x87, 0xd8, 0x53, 0x18, 0x9b,
	0x34, 0xd7, 0x1c, 0xc8, 0x12, 0x90, 0xe5, 0x36, 0xcd, 0xb5, 0x20, 0x39, 0xd9, 0xc3, 0xcc, 0x0d,
	0xe9, 0x6d, 0xbb, 0x17, 0xf6, 0x11, 0xfc, 0xeb, 0xfa, 0x80, 0x9f, 0x25, 0x7b, 0x7e, 0x62, 0x63,
	0xee, 0xb1, 0x85, 0x2f, 0x4e, 0xd9, 0xdc, 0x8b, 0x58, 0x3e, 0x58, 0xbf, 0xfc, 0x14, 0xe7, 0x85,
	0xd9, 0xdb, 0x4d, 0x94, 0x61, 0x15, 0x57, 0x45, 0xa6, 0x50, 0xe3, 0xce, 0xc4, 0x15, 0x66, 0xb1,
	0x6a, 0xb2, 0x78, 0xc8, 0x88, 0xfb, 0x8c, 0x8d, 0x4f, 0x4b, 0x7f, 0xf5, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0xb4, 0x9d, 0xbd, 0xc8, 0x50, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecretAgentClient is the client API for SecretAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecretAgentClient interface {
	Invoke(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*SecretResponse, error)
}

type secretAgentClient struct {
	cc *grpc.ClientConn
}

func NewSecretAgentClient(cc *grpc.ClientConn) SecretAgentClient {
	return &secretAgentClient{cc}
}

func (c *secretAgentClient) Invoke(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*SecretResponse, error) {
	out := new(SecretResponse)
	err := c.cc.Invoke(ctx, "/moc.hostagent.security.SecretAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretAgentServer is the server API for SecretAgent service.
type SecretAgentServer interface {
	Invoke(context.Context, *SecretRequest) (*SecretResponse, error)
}

// UnimplementedSecretAgentServer can be embedded to have forward compatible implementations.
type UnimplementedSecretAgentServer struct {
}

func (*UnimplementedSecretAgentServer) Invoke(ctx context.Context, req *SecretRequest) (*SecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterSecretAgentServer(s *grpc.Server, srv SecretAgentServer) {
	s.RegisterService(&_SecretAgent_serviceDesc, srv)
}

func _SecretAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.hostagent.security.SecretAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretAgentServer).Invoke(ctx, req.(*SecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecretAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.hostagent.security.SecretAgent",
	HandlerType: (*SecretAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _SecretAgent_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_hostagent_secret.proto",
}
